namespace RobinEpple.Common.Html.Mdn;

using System.Text;
using HtmlAgilityPack;

public static class HtmlTags
{
	public static IEnumerable<HtmlTag> FetchAll(
		string overviewUrl,
		string tagBaseUrl,
		string classNamespace,
		IDictionary<string, IEnumerable<string>> groupedTags
	)
	{
		var results = new List<HtmlTag>();
		var domain = overviewUrl.Split("/", StringSplitOptions.RemoveEmptyEntries)[1];

		var web = new HtmlWeb();
		var doc = web.Load(overviewUrl);

		// Find all the "Elements" navigation header.
		var navigationHeaders = doc.DocumentNode.SelectNodes("//summary");
		if (navigationHeaders == null)
		{
			return results;
		}
		var elementsHeader = navigationHeaders.FirstOrDefault(header =>
			Helper.GetPlainText(header).Trim() == "Elements"
		);
		if (elementsHeader == null)
		{
			return results;
		}

		// Find the directly following <ol>
		var ol = elementsHeader.SelectSingleNode("following-sibling::ol[1]");
		if (ol == null)
		{
			return results;
		}

		// Find all contained links.
		var tagLinks = ol.SelectNodes(".//a");

		// Isolate a distinct set of links pointing to html tag documentations.
		var tagUrls = new HashSet<string>();
		foreach (var a in tagLinks)
		{
			var link = a.GetAttributeValue("href", "").Trim();
			if (string.IsNullOrEmpty(link))
			{
				continue;
			}

			if (!link.StartsWith(tagBaseUrl))
			{
				continue;
			}

			var tagUrl = $"https://{domain}{link}";
			tagUrls.Add(tagUrl);
		}

		// Then fetch the documentation for each tag.
		foreach (var tagUrl in tagUrls)
		{
			results.AddRange(Fetch(tagUrl, classNamespace, groupedTags));
		}

		return results;
	}

	public static IEnumerable<HtmlTag> Fetch(
		string url,
		string classNamespace,
		IDictionary<string, IEnumerable<string>> groupedTags
	)
	{
		Console.WriteLine($"Fetching {url}");
		var tagName = url.Split("/").Last();
		var className = Helper.PascalCase(tagName);

		var web = new HtmlWeb();
		var doc = web.Load(url);

		// Get deprecated information.

		var deprecatedSection = doc.DocumentNode.SelectSingleNode("//div[contains(@class, 'deprecated')]");
		var isDeprecated = deprecatedSection != null;

		// Find the first content section -> contains the element documentation.
		var documentation = string.Empty;
		var docSection = doc.DocumentNode.SelectSingleNode("//section[contains(@class, 'content-section')]");
		if (docSection != null)
		{
			documentation = Helper.GetPlainText(docSection);
		}

		// Fetch attributes.
		var attributes = HtmlAttributes.ParseFrom(doc, url);

		if (!groupedTags.TryGetValue(tagName, out var groupedTagNames))
		{
			return [new HtmlTag(classNamespace, className, tagName, documentation, attributes, isDeprecated, url)];
		}

		var documentationAppendix =
			$"This is one variant of the following tag group: {string.Join(", ", groupedTagNames)}.\n";
		return groupedTagNames.Select(groupedTag => new HtmlTag(
			classNamespace,
			Helper.PascalCase(groupedTag),
			groupedTag,
			documentationAppendix + documentation,
			attributes,
			isDeprecated,
			url
		));
	}

	public static string Render(
		HtmlTag tag,
		HashSet<string> excludeAttributes,
		HashSet<string> globalAttributes,
		HashSet<string> voidElements
	)
	{
		var sb = new StringBuilder();

		// Namespace and usings.
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine(Helper.PrintMdnLicenseHeader(tag.MdnUrl));
		sb.AppendLine("#nullable enable");
		sb.AppendLine($"namespace {tag.Namespace};");
		sb.AppendLine();
		sb.AppendLine("using RobinEpple.Common.Html;");
		sb.AppendLine("using RobinEpple.Common.Html.Components;");
		sb.AppendLine("using Microsoft.AspNetCore.Html;");
		sb.AppendLine("using static RobinEpple.Common.Html.DSL;");

		// Class declaration and constructors.
		var isVoidElement = voidElements.Contains(tag.TagName);
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine(Helper.PrintMdnDocumentation(tag.Documentation, tag.MdnUrl));
		sb.AppendLine("/// </summary>");
		if (tag.IsDeprecated)
		{
			sb.AppendLine($"[Obsolete]");
		}
		sb.AppendLine($"public partial class {tag.ClassName}");
		sb.AppendLine(Helper.Indent($": HtmlTag"));
		sb.AppendLine("{");
		if (isVoidElement)
		{
			sb.AppendLine(Helper.Indent("/// <summary>"));
			sb.AppendLine(Helper.Indent(Helper.PrintMdnDocumentation(tag.Documentation, tag.MdnUrl)));
			sb.AppendLine(Helper.Indent("/// </summary>"));
			sb.AppendLine(Helper.Indent($"public {tag.ClassName}()"));
			sb.AppendLine(Helper.Indent($": base(\"{tag.TagName}\", true)", 2));
			sb.AppendLine(Helper.Indent("{"));
			sb.AppendLine(Helper.Indent("}"));
		}
		else
		{
			sb.AppendLine(Helper.Indent("/// <summary>"));
			sb.AppendLine(Helper.Indent(Helper.PrintMdnDocumentation(tag.Documentation, tag.MdnUrl)));
			sb.AppendLine(Helper.Indent("/// </summary>"));
			sb.AppendLine(Helper.Indent("/// <param name=\"contents\">"));
			sb.AppendLine(
				Helper.Indent(Helper.PrintDocumentation("A list of HTML contents to place inside this element."))
			);
			sb.AppendLine(Helper.Indent("/// </param>"));
			sb.AppendLine(Helper.Indent($"public {tag.ClassName}(params IEnumerable<IHtmlContent> contents)"));
			sb.AppendLine(Helper.Indent($": base(\"{tag.TagName}\", false, contents)", 2));
			sb.AppendLine(Helper.Indent("{"));
			sb.AppendLine(Helper.Indent("}"));
			sb.AppendLine();
			sb.AppendLine(Helper.Indent("/// <summary>"));
			sb.AppendLine(Helper.Indent(Helper.PrintMdnDocumentation(tag.Documentation, tag.MdnUrl)));
			sb.AppendLine(Helper.Indent("/// </summary>"));
			sb.AppendLine(Helper.Indent("/// <param name=\"text\">"));
			sb.AppendLine(
				Helper.Indent(
					Helper.PrintDocumentation("Some text to write inside this element. The text will be encoded.")
				)
			);
			sb.AppendLine(Helper.Indent("/// </param>"));
			sb.AppendLine(Helper.Indent($"public {tag.ClassName}(string text)"));
			sb.AppendLine(Helper.Indent($": this(Encode(text))", 2));
			sb.AppendLine(Helper.Indent("{"));
			sb.AppendLine(Helper.Indent("}"));
		}

		// Attributes.
		foreach (var attribute in tag.Attributes.OrderBy(attribute => attribute.Name))
		{
			if (excludeAttributes.Contains(attribute.Name))
			{
				continue;
			}
			var isGlobalOverride = globalAttributes.Contains(attribute.Name);
			sb.AppendLine(Helper.Indent(HtmlAttributes.Render(attribute, tag.ClassName, isGlobalOverride)));
		}

		// Close class.
		sb.AppendLine("}");
		return sb.ToString();
	}
}
