<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>RobinEpple.Common.Util</AssemblyName>
		<PackageId>RobinEpple.Common.Util</PackageId>
		<RootNamespace>RobinEpple.Common.Util</RootNamespace>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>Private Common Utilities</Title>
		<Version>1.0.0.0</Version>
	</PropertyGroup>

</Project>