// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;

/// <summary>
/// The <address> HTML element indicates that the enclosed HTML provides contact information for a person or people, or for an organization.
/// </summary>
public partial class Address(IHtmlContent content)
	: HtmlTag("address", false, content)
{
}
