// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;audio&gt; HTML element is used to embed sound content in documents. It may contain one or more audio sources, represented using the src attribute or the &lt;source&gt; element: the browser will choose the most suitable one.
/// It can also be the destination for streamed media, using a MediaStream.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
/// </summary>
public partial class Audio
	: HtmlTag
{
	/// <summary>
	/// The &lt;audio&gt; HTML element is used to embed sound content in documents. It may contain one or more audio sources, represented using the src attribute or the &lt;source&gt; element: the browser will choose the most suitable one.
	/// It can also be the destination for streamed media, using a MediaStream.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Audio(params IEnumerable<IHtmlContent> contents)
		: base("audio", false, contents)
	{
	}

	/// <summary>
	/// The &lt;audio&gt; HTML element is used to embed sound content in documents. It may contain one or more audio sources, represented using the src attribute or the &lt;source&gt; element: the browser will choose the most suitable one.
	/// It can also be the destination for streamed media, using a MediaStream.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Audio(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// Sends a cross-origin request without a credential. In other words, it sends the Origin: HTTP header without a cookie, X.509 certificate, or performing HTTP Basic authentication. If the server does not give credentials to the origin site (by not setting the Access-Control-Allow-Origin: HTTP header), the resource will be tainted, and its usage restricted.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Anonymous(string value)
	{
		return this.Attribute("anonymous", value);
	}

	/// <summary>
	/// The input buffer of a ScriptProcessorNode is ready to be processed.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	[Obsolete]
	public Audio Audioprocess(string value)
	{
		return this.Attribute("audioprocess", value);
	}

	/// <summary>
	/// A Boolean attribute: if specified, the audio will automatically begin playback as soon as it can do so, without waiting for the entire audio file to finish downloading.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Autoplay(string value)
	{
		return this.Attribute("autoplay", value);
	}

	/// <summary>
	/// The browser can play the media, but estimates that not enough data has been loaded to play the media up to its end without having to stop for further buffering of content.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Canplay(string value)
	{
		return this.Attribute("canplay", value);
	}

	/// <summary>
	/// The browser estimates it can play the media up to its end without stopping for content buffering.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Canplaythrough(string value)
	{
		return this.Attribute("canplaythrough", value);
	}

	/// <summary>
	/// The rendering of an OfflineAudioContext is terminated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Complete(string value)
	{
		return this.Attribute("complete", value);
	}

	/// <summary>
	/// If this attribute is present, the browser will offer controls to allow the user to control audio playback, including volume, seeking, and pause/resume playback.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Controls(string value)
	{
		return this.Attribute("controls", value);
	}

	/// <summary>
	/// The controlslist attribute, when specified, helps the browser select what controls to show for the audio element whenever the browser shows its own set of controls (that is, when the controls attribute is specified).
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Controlslist(string value)
	{
		return this.Attribute("controlslist", value);
	}

	/// <summary>
	/// This enumerated attribute indicates whether to use CORS to fetch the related audio file. CORS-enabled resources can be reused in the &lt;canvas&gt; element without being tainted. The allowed values are:
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Crossorigin(string value)
	{
		return this.Attribute("crossorigin", value);
	}

	/// <summary>
	/// A Boolean attribute used to disable the capability of remote playback in devices that are attached using wired (HDMI, DVI, etc.) and wireless technologies (Miracast, Chromecast, DLNA, AirPlay, etc.). See the proposed Remote Playback API specification for more information.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Disableremoteplayback(string value)
	{
		return this.Attribute("disableremoteplayback", value);
	}

	/// <summary>
	/// The duration attribute has been updated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Durationchange(string value)
	{
		return this.Attribute("durationchange", value);
	}

	/// <summary>
	/// The media has become empty; for example, this event is sent if the media has already been loaded (or partially loaded), and the HTMLMediaElement.load method is called to reload it.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Emptied(string value)
	{
		return this.Attribute("emptied", value);
	}

	/// <summary>
	/// Playback has stopped because the end of the media was reached.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Ended(string value)
	{
		return this.Attribute("ended", value);
	}

	/// <summary>
	/// An AudioTrackList containing all of the media element&apos;s audio tracks. You can add a listener for addtrack to this object to be alerted when new audio tracks are added to the element.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio HtmlmediaelementAudiotracks(string value)
	{
		return this.Attribute("htmlmediaelement.audiotracks", value);
	}

	/// <summary>
	/// Add an addtrack event listener to this TextTrackList to be notified when new text tracks are added to the element.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio HtmlmediaelementTexttracks(string value)
	{
		return this.Attribute("htmlmediaelement.texttracks", value);
	}

	/// <summary>
	/// Add an addtrack listener to this VideoTrackList object to be informed when video tracks are added to the element.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio HtmlmediaelementVideotracks(string value)
	{
		return this.Attribute("htmlmediaelement.videotracks", value);
	}

	/// <summary>
	/// The first frame of the media has finished loading.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Loadeddata(string value)
	{
		return this.Attribute("loadeddata", value);
	}

	/// <summary>
	/// The metadata has been loaded.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Loadedmetadata(string value)
	{
		return this.Attribute("loadedmetadata", value);
	}

	/// <summary>
	/// Fired when the browser has started to load the resource.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Loadstart(string value)
	{
		return this.Attribute("loadstart", value);
	}

	/// <summary>
	/// A Boolean attribute: if specified, the audio player will automatically seek back to the start upon reaching the end of the audio.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Loop(string value)
	{
		return this.Attribute("loop", value);
	}

	/// <summary>
	/// A Boolean attribute that indicates whether the audio will be initially silenced. Its default value is false.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Muted(string value)
	{
		return this.Attribute("muted", value);
	}

	/// <summary>
	/// Playback has been paused.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Pause(string value)
	{
		return this.Attribute("pause", value);
	}

	/// <summary>
	/// Playback has begun.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Play(string value)
	{
		return this.Attribute("play", value);
	}

	/// <summary>
	/// Playback is ready to start after having been paused or delayed due to lack of data.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Playing(string value)
	{
		return this.Attribute("playing", value);
	}

	/// <summary>
	/// This enumerated attribute is intended to provide a hint to the browser about what the author thinks will lead to the best user experience. It may have one of the following values:
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Preload(string value)
	{
		return this.Attribute("preload", value);
	}

	/// <summary>
	/// The playback rate has changed.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Ratechange(string value)
	{
		return this.Attribute("ratechange", value);
	}

	/// <summary>
	/// A seek operation completed.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Seeked(string value)
	{
		return this.Attribute("seeked", value);
	}

	/// <summary>
	/// A seek operation began.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Seeking(string value)
	{
		return this.Attribute("seeking", value);
	}

	/// <summary>
	/// The URL of the audio to embed. This is subject to HTTP access controls. This is optional; you may instead use the &lt;source&gt; element within the audio block to specify the audio to embed.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Src(string value)
	{
		return this.Attribute("src", value);
	}

	/// <summary>
	/// The user agent is trying to fetch media data, but data is unexpectedly not forthcoming.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Stalled(string value)
	{
		return this.Attribute("stalled", value);
	}

	/// <summary>
	/// Media data loading has been suspended.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Suspend(string value)
	{
		return this.Attribute("suspend", value);
	}

	/// <summary>
	/// The time indicated by the currentTime attribute has been updated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Timeupdate(string value)
	{
		return this.Attribute("timeupdate", value);
	}

	/// <summary>
	/// Sends a cross-origin request with a credential. In other words, it sends the Origin: HTTP header with a cookie, a certificate, or performing HTTP Basic authentication. If the server does not give credentials to the origin site (through Access-Control-Allow-Credentials: HTTP header), the resource will be tainted and its usage restricted.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio UseCredentials(string value)
	{
		return this.Attribute("use-credentials", value);
	}

	/// <summary>
	/// The volume has changed.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Volumechange(string value)
	{
		return this.Attribute("volumechange", value);
	}

	/// <summary>
	/// Playback has stopped because of a temporary lack of data.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/audio
	/// </summary>
	public Audio Waiting(string value)
	{
		return this.Attribute("waiting", value);
	}

}
