// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdi

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;bdi&gt; HTML element tells the browser&apos;s bidirectional algorithm to treat the text it contains in isolation from its surrounding text. It&apos;s particularly useful when a website dynamically inserts some text and doesn&apos;t know the directionality of the text being inserted.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdi
/// </summary>
public partial class Bdi
	: HtmlTag
{
	/// <summary>
	/// The &lt;bdi&gt; HTML element tells the browser&apos;s bidirectional algorithm to treat the text it contains in isolation from its surrounding text. It&apos;s particularly useful when a website dynamically inserts some text and doesn&apos;t know the directionality of the text being inserted.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdi
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Bdi(params IEnumerable<IHtmlContent> contents)
		: base("bdi", false, contents)
	{
	}

	/// <summary>
	/// The &lt;bdi&gt; HTML element tells the browser&apos;s bidirectional algorithm to treat the text it contains in isolation from its surrounding text. It&apos;s particularly useful when a website dynamically inserts some text and doesn&apos;t know the directionality of the text being inserted.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdi
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Bdi(string text)
		: this(Encode(text))
	{
	}
}
