// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdo
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;bdo&gt; HTML element overrides the current directionality of text, so that the text within is rendered in a different direction.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdo
///<br/> - by Mozilla Contributors
/// </summary>
public partial class Bdo
	: HtmlTag
{
	/// <summary>
	/// The &lt;bdo&gt; HTML element overrides the current directionality of text, so that the text within is rendered in a different direction.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdo
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Bdo(params IEnumerable<IHtmlContent> contents)
		: base("bdo", false, contents)
	{
	}

	/// <summary>
	/// The &lt;bdo&gt; HTML element overrides the current directionality of text, so that the text within is rendered in a different direction.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdo
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Bdo(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// The direction in which text should be rendered in this element&apos;s contents. Possible values are:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/bdo
	///<br/> - by Mozilla Contributors
	/// </summary>
	public new Bdo Dir(string value)
	{
		return this.Attribute("dir", value);
	}

}
