// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/blockquote
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;blockquote&gt; HTML element indicates that the enclosed text is an extended quotation. Usually, this is rendered visually by indentation (see Notes for how to change it). A URL for the source of the quotation may be given using the cite attribute, while a text representation of the source can be given using the &lt;cite&gt; element.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/blockquote
///<br/> - by Mozilla Contributors
/// </summary>
public partial class Blockquote
	: HtmlTag
{
	/// <summary>
	/// The &lt;blockquote&gt; HTML element indicates that the enclosed text is an extended quotation. Usually, this is rendered visually by indentation (see Notes for how to change it). A URL for the source of the quotation may be given using the cite attribute, while a text representation of the source can be given using the &lt;cite&gt; element.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/blockquote
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Blockquote(params IEnumerable<IHtmlContent> contents)
		: base("blockquote", false, contents)
	{
	}

	/// <summary>
	/// The &lt;blockquote&gt; HTML element indicates that the enclosed text is an extended quotation. Usually, this is rendered visually by indentation (see Notes for how to change it). A URL for the source of the quotation may be given using the cite attribute, while a text representation of the source can be given using the &lt;cite&gt; element.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/blockquote
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Blockquote(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// A URL that designates a source document or message for the information quoted. This attribute is intended to point to information explaining the context or the reference for the quote.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/blockquote
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Blockquote Cite(string value)
	{
		return this.Attribute("cite", value);
	}

}
