// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;button&gt; HTML element is an interactive element activated by a user with a mouse, keyboard, finger, voice command, or other assistive technology. Once activated, it then performs an action, such as submitting a form or opening a dialog. By default, HTML buttons are presented in a style resembling the platform the user agent runs on, but you can change buttons&apos; appearance with CSS.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
///<br/> - by Mozilla Contributors
/// </summary>
public partial class Button
	: HtmlTag
{
	/// <summary>
	/// The &lt;button&gt; HTML element is an interactive element activated by a user with a mouse, keyboard, finger, voice command, or other assistive technology. Once activated, it then performs an action, such as submitting a form or opening a dialog. By default, HTML buttons are presented in a style resembling the platform the user agent runs on, but you can change buttons&apos; appearance with CSS.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Button(params IEnumerable<IHtmlContent> contents)
		: base("button", false, contents)
	{
	}

	/// <summary>
	/// The &lt;button&gt; HTML element is an interactive element activated by a user with a mouse, keyboard, finger, voice command, or other assistive technology. Once activated, it then performs an action, such as submitting a form or opening a dialog. By default, HTML buttons are presented in a style resembling the platform the user agent runs on, but you can change buttons&apos; appearance with CSS.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Button(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// This Boolean attribute specifies that the button should have input focus when the page loads. Only one element in a document can have this attribute.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public new Button Autofocus(string value)
	{
		return this.Attribute("autofocus", value);
	}

	/// <summary>
	/// The button will close a &lt;dialog&gt; element.
	/// If the dialog is already closed, no action will be taken.
	/// This is a declarative equivalent of calling the HTMLDialogElement.close() method on the &lt;dialog&gt; element.
	/// When used with the value attribute, the button&apos;s value will be passed as the dialog&apos;s returnValue property.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Close(string value)
	{
		return this.Attribute("close", value);
	}

	/// <summary>
	/// Specifies the action to be performed on an element being controlled by a control &lt;button&gt; specified via the commandfor attribute. The possible values are:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Command(string value)
	{
		return this.Attribute("command", value);
	}

	/// <summary>
	/// Turns a &lt;button&gt; element into a command button, controlling a given interactive element by issuing the command specified in the button&apos;s command attribute. The commandfor attribute takes the ID of the element to control as its value. This is a more general version of popovertarget.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Commandfor(string value)
	{
		return this.Attribute("commandfor", value);
	}

	/// <summary>
	/// This attribute can represent custom values that are prefixed with a two hyphen characters ( -- ). Buttons with a custom value will dispatch the CommandEvent on the controlled element.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button CustomValues(string value)
	{
		return this.Attribute("custom_values", value);
	}

	/// <summary>
	/// This Boolean attribute prevents the user from interacting with the button: it cannot be pressed or focused.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Disabled(string value)
	{
		return this.Attribute("disabled", value);
	}

	/// <summary>
	/// The &lt;form&gt; element to associate the button with (its form owner ). The value of this attribute must be the id of a &lt;form&gt; in the same document. (If this attribute is not set, the &lt;button&gt; is associated with its ancestor &lt;form&gt; element, if any.)
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Form(string value)
	{
		return this.Attribute("form", value);
	}

	/// <summary>
	/// The URL that processes the information submitted by the button. Overrides the action attribute of the button&apos;s form owner. Does nothing if there is no form owner.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Formaction(string value)
	{
		return this.Attribute("formaction", value);
	}

	/// <summary>
	/// If the button is a submit button (it&apos;s inside/associated with a &lt;form&gt; and doesn&apos;t have type=&quot;button&quot; ), specifies how to encode the form data that is submitted. Possible values:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Formenctype(string value)
	{
		return this.Attribute("formenctype", value);
	}

	/// <summary>
	/// If the button is a submit button (it&apos;s inside/associated with a &lt;form&gt; and doesn&apos;t have type=&quot;button&quot; ), this attribute specifies the HTTP method used to submit the form. Possible values:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Formmethod(string value)
	{
		return this.Attribute("formmethod", value);
	}

	/// <summary>
	/// If the button is a submit button, this Boolean attribute specifies that the form is not to be validated when it is submitted. If this attribute is specified, it overrides the novalidate attribute of the button&apos;s form owner.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Formnovalidate(string value)
	{
		return this.Attribute("formnovalidate", value);
	}

	/// <summary>
	/// If the button is a submit button, this attribute is an author-defined name or standardized, underscore-prefixed keyword indicating where to display the response from submitting the form. This is the name of, or keyword for, a browsing context (a tab, window, or &lt;iframe&gt; ). If this attribute is specified, it overrides the target attribute of the button&apos;s form owner. The following keywords have special meanings:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Formtarget(string value)
	{
		return this.Attribute("formtarget", value);
	}

	/// <summary>
	/// The button will hide a shown popover. If you try to hide an already hidden popover, no action will be taken.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Hide(string value)
	{
		return this.Attribute("hide", value);
	}

	/// <summary>
	/// The button will hide a showing popover. If you try to hide an already hidden popover, no action will be taken. See Popover API for more details. This is equivalent to setting a value of hide for the popovertargetaction attribute, and also provides a declarative equivalent to calling the HTMLElement.hidePopover() method on the popover element.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button HidePopover(string value)
	{
		return this.Attribute("hide-popover", value);
	}

	/// <summary>
	/// Defines the &lt;button&gt; element as an interest invoker. Its value is the id of a target element, which will be affected in some way (normally shown or hidden) when interest is shown or lost on the invoker element (for example, by hovering/unhovering or focusing/blurring it). See Using interest invokers for more details and examples.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Interestfor(string value)
	{
		return this.Attribute("interestfor", value);
	}

	/// <summary>
	/// The name of the button, submitted as a pair with the button&apos;s value as part of the form data, when that button is used to submit the form.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Name(string value)
	{
		return this.Attribute("name", value);
	}

	/// <summary>
	/// Turns a &lt;button&gt; element into a popover control button; takes the ID of the popover element to control as its value. Establishing a relationship between a popover and its invoker button using the popovertarget attribute has two additional useful effects:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Popovertarget(string value)
	{
		return this.Attribute("popovertarget", value);
	}

	/// <summary>
	/// Specifies the action to be performed on a popover element being controlled by a control &lt;button&gt;. Possible values are:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Popovertargetaction(string value)
	{
		return this.Attribute("popovertargetaction", value);
	}

	/// <summary>
	/// The button will trigger a cancel event on a &lt;dialog&gt; element to request that the browser dismiss it, followed by a close event.
	/// This differs from the close command in that authors can call Event.preventDefault() on the cancel event to prevent the &lt;dialog&gt; from closing.
	/// If the dialog is already closed, no action will be taken.
	/// This is a declarative equivalent of calling the HTMLDialogElement.requestClose() method on the &lt;dialog&gt; element.
	/// When used with the button&apos;s value attribute, the value will be passed as the dialog&apos;s returnValue property.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button RequestClose(string value)
	{
		return this.Attribute("request-close", value);
	}

	/// <summary>
	/// The button will show a hidden popover. If you try to show an already showing popover, no action will be taken.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Show(string value)
	{
		return this.Attribute("show", value);
	}

	/// <summary>
	/// The button will show a &lt;dialog&gt; as modal. If the dialog is already modal, no action will be taken. This is a declarative equivalent of calling the HTMLDialogElement.showModal() method on the &lt;dialog&gt; element.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button ShowModal(string value)
	{
		return this.Attribute("show-modal", value);
	}

	/// <summary>
	/// The button will show a hidden popover. If you try to show an already showing popover, no action will be taken. See Popover API for more details. This is equivalent to setting a value of show for the popovertargetaction attribute, and also provides a declarative equivalent to calling the HTMLElement.showPopover() method on the popover element.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button ShowPopover(string value)
	{
		return this.Attribute("show-popover", value);
	}

	/// <summary>
	/// The button will toggle a popover between showing and hidden. If the popover is hidden, it will be shown; if the popover is showing, it will be hidden. If popovertargetaction is omitted, &quot;toggle&quot; is the default action that will be performed by the control button.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Toggle(string value)
	{
		return this.Attribute("toggle", value);
	}

	/// <summary>
	/// The button will toggle a popover between showing and hidden. If the popover is hidden, it will be shown; if the popover is showing, it will be hidden. See Popover API for more details. This is equivalent to setting a value of toggle for the popovertargetaction attribute, and also provides a declarative equivalent to calling the HTMLElement.togglePopover() method on the popover element.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button TogglePopover(string value)
	{
		return this.Attribute("toggle-popover", value);
	}

	/// <summary>
	/// The default behavior of the button. Possible values are:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Type(string value)
	{
		return this.Attribute("type", value);
	}

	/// <summary>
	/// Defines the value associated with the button&apos;s name when it&apos;s submitted with the form data.
	/// This value is passed to the server in params when the form is submitted using this button.
	/// When used with the close or request-close commands, the value attribute sets the returnValue of the &lt;dialog&gt; element being controlled.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Button Value(string value)
	{
		return this.Attribute("value", value);
	}

}
