// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The <button> HTML element is an interactive element activated by a user with a mouse, keyboard, finger, voice command, or other assistive technology. Once activated, it then performs an action, such as submitting a form or opening a dialog. By default, HTML buttons are presented in a style resembling the platform the user agent runs on, but you can change buttons' appearance with CSS.
/// </summary>
public partial class Button(params IEnumerable<IHtmlContent> contents)
	: HtmlTag("button", false, contents)
{
	public Button(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// This Boolean attribute specifies that the button should have input focus when the page loads. Only one element in a document can have this attribute.
	/// </summary>
	public new Button Autofocus(string value)
	{
		return this.Attribute("autofocus", value);
	}

	/// <summary>
	/// The button will close a <dialog> element. If the dialog is already closed, no action will be taken. This is a declarative equivalent of calling the HTMLDialogElement.close() method on the <dialog> element.
	/// </summary>
	public Button Close(string value)
	{
		return this.Attribute("close", value);
	}

	/// <summary>
	/// Specifies the action to be performed on an element being controlled by a control <button> specified via the commandfor attribute. The possible values are:
	/// </summary>
	public Button Command(string value)
	{
		return this.Attribute("command", value);
	}

	/// <summary>
	/// Turns a <button> element into a command button, controlling a given interactive element by issuing the command specified in the button's command attribute. The commandfor attribute takes the ID of the element to control as its value. This is a more general version of popovertarget.
	/// </summary>
	public Button Commandfor(string value)
	{
		return this.Attribute("commandfor", value);
	}

	/// <summary>
	/// This attribute can represent custom values that are prefixed with a two hyphen characters ( -- ). Buttons with a custom value will dispatch the CommandEvent on the controlled element.
	/// </summary>
	public Button CustomValues(string value)
	{
		return this.Attribute("custom_values", value);
	}

	/// <summary>
	/// This Boolean attribute prevents the user from interacting with the button: it cannot be pressed or focused.
	/// </summary>
	public Button Disabled(string value)
	{
		return this.Attribute("disabled", value);
	}

	/// <summary>
	/// The <form> element to associate the button with (its form owner ). The value of this attribute must be the id of a <form> in the same document. (If this attribute is not set, the <button> is associated with its ancestor <form> element, if any.)
	/// </summary>
	public Button Form(string value)
	{
		return this.Attribute("form", value);
	}

	/// <summary>
	/// The URL that processes the information submitted by the button. Overrides the action attribute of the button's form owner. Does nothing if there is no form owner.
	/// </summary>
	public Button Formaction(string value)
	{
		return this.Attribute("formaction", value);
	}

	/// <summary>
	/// If the button is a submit button (it's inside/associated with a <form> and doesn't have type="button" ), specifies how to encode the form data that is submitted. Possible values:
	/// </summary>
	public Button Formenctype(string value)
	{
		return this.Attribute("formenctype", value);
	}

	/// <summary>
	/// If the button is a submit button (it's inside/associated with a <form> and doesn't have type="button" ), this attribute specifies the HTTP method used to submit the form. Possible values:
	/// </summary>
	public Button Formmethod(string value)
	{
		return this.Attribute("formmethod", value);
	}

	/// <summary>
	/// If the button is a submit button, this Boolean attribute specifies that the form is not to be validated when it is submitted. If this attribute is specified, it overrides the novalidate attribute of the button's form owner.
	/// </summary>
	public Button Formnovalidate(string value)
	{
		return this.Attribute("formnovalidate", value);
	}

	/// <summary>
	/// If the button is a submit button, this attribute is an author-defined name or standardized, underscore-prefixed keyword indicating where to display the response from submitting the form. This is the name of, or keyword for, a browsing context (a tab, window, or <iframe> ). If this attribute is specified, it overrides the target attribute of the button's form owner. The following keywords have special meanings:
	/// </summary>
	public Button Formtarget(string value)
	{
		return this.Attribute("formtarget", value);
	}

	/// <summary>
	/// The button will hide a shown popover. If you try to hide an already hidden popover, no action will be taken.
	/// </summary>
	public Button Hide(string value)
	{
		return this.Attribute("hide", value);
	}

	/// <summary>
	/// The button will hide a showing popover. If you try to hide an already hidden popover, no action will be taken. See Popover API for more details. This is equivalent to setting a value of hide for the popovertargetaction attribute, and also provides a declarative equivalent to calling the HTMLElement.hidePopover() method on the popover element.
	/// </summary>
	public Button HidePopover(string value)
	{
		return this.Attribute("hide-popover", value);
	}

	/// <summary>
	/// Defines the <button> element as an interest invoker. Its value is the id of a target element, which will be affected in some way (normally shown or hidden) when interest is shown or lost on the invoker element (for example, by hovering/unhovering or focusing/blurring it). See Using interest invokers for more details and examples.
	/// </summary>
	public Button Interestfor(string value)
	{
		return this.Attribute("interestfor", value);
	}

	/// <summary>
	/// The name of the button, submitted as a pair with the button's value as part of the form data, when that button is used to submit the form.
	/// </summary>
	public Button Name(string value)
	{
		return this.Attribute("name", value);
	}

	/// <summary>
	/// Turns a <button> element into a popover control button; takes the ID of the popover element to control as its value. Establishing a relationship between a popover and its invoker button using the popovertarget attribute has two additional useful effects:
	/// </summary>
	public Button Popovertarget(string value)
	{
		return this.Attribute("popovertarget", value);
	}

	/// <summary>
	/// Specifies the action to be performed on a popover element being controlled by a control <button>. Possible values are:
	/// </summary>
	public Button Popovertargetaction(string value)
	{
		return this.Attribute("popovertargetaction", value);
	}

	/// <summary>
	/// The button will trigger a cancel event on a <dialog> element to request that the browser dismiss it, followed by a close event. This differs from the close command in that authors can call Event.preventDefault() on the cancel event to prevent the <dialog> from closing. If the dialog is already closed, no action will be taken. This is a declarative equivalent of calling the HTMLDialogElement.requestClose() method on the <dialog> element.
	/// </summary>
	public Button RequestClose(string value)
	{
		return this.Attribute("request-close", value);
	}

	/// <summary>
	/// The button will show a hidden popover. If you try to show an already showing popover, no action will be taken.
	/// </summary>
	public Button Show(string value)
	{
		return this.Attribute("show", value);
	}

	/// <summary>
	/// The button will show a <dialog> as modal. If the dialog is already modal, no action will be taken. This is a declarative equivalent of calling the HTMLDialogElement.showModal() method on the <dialog> element.
	/// </summary>
	public Button ShowModal(string value)
	{
		return this.Attribute("show-modal", value);
	}

	/// <summary>
	/// The button will show a hidden popover. If you try to show an already showing popover, no action will be taken. See Popover API for more details. This is equivalent to setting a value of show for the popovertargetaction attribute, and also provides a declarative equivalent to calling the HTMLElement.showPopover() method on the popover element.
	/// </summary>
	public Button ShowPopover(string value)
	{
		return this.Attribute("show-popover", value);
	}

	/// <summary>
	/// The button will toggle a popover between showing and hidden. If the popover is hidden, it will be shown; if the popover is showing, it will be hidden. If popovertargetaction is omitted, "toggle" is the default action that will be performed by the control button.
	/// </summary>
	public Button Toggle(string value)
	{
		return this.Attribute("toggle", value);
	}

	/// <summary>
	/// The button will toggle a popover between showing and hidden. If the popover is hidden, it will be shown; if the popover is showing, it will be hidden. See Popover API for more details. This is equivalent to setting a value of toggle for the popovertargetaction attribute, and also provides a declarative equivalent to calling the HTMLElement.togglePopover() method on the popover element.
	/// </summary>
	public Button TogglePopover(string value)
	{
		return this.Attribute("toggle-popover", value);
	}

	/// <summary>
	/// The default behavior of the button. Possible values are:
	/// </summary>
	public Button Type(string value)
	{
		return this.Attribute("type", value);
	}

	/// <summary>
	/// Defines the value associated with the button's name when it's submitted with the form data. This value is passed to the server in params when the form is submitted using this button.
	/// </summary>
	public Button Value(string value)
	{
		return this.Attribute("value", value);
	}

}
