// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/cite

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;cite&gt; HTML element is used to mark up the title of a creative work. The reference may be in an abbreviated form according to context-appropriate conventions related to citation metadata.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/cite
/// </summary>
public partial class Cite
	: HtmlTag
{
	/// <summary>
	/// The &lt;cite&gt; HTML element is used to mark up the title of a creative work. The reference may be in an abbreviated form according to context-appropriate conventions related to citation metadata.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/cite
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Cite(params IEnumerable<IHtmlContent> contents)
		: base("cite", false, contents)
	{
	}

	/// <summary>
	/// The &lt;cite&gt; HTML element is used to mark up the title of a creative work. The reference may be in an abbreviated form according to context-appropriate conventions related to citation metadata.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/cite
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Cite(string text)
		: this(Encode(text))
	{
	}
}
