// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;col&gt; HTML element defines one or more columns in a column group represented by its parent &lt;colgroup&gt; element. The &lt;col&gt; element is only valid as a child of a &lt;colgroup&gt; element that has no span attribute defined.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
///<br/> - by Mozilla Contributors
/// </summary>
public partial class Col
	: HtmlTag
{
	/// <summary>
	/// The &lt;col&gt; HTML element defines one or more columns in a column group represented by its parent &lt;colgroup&gt; element. The &lt;col&gt; element is only valid as a child of a &lt;colgroup&gt; element that has no span attribute defined.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Col()
		: base("col", true)
	{
	}
	/// <summary>
	/// Specifies the horizontal alignment of each column cell. The possible enumerated values are left, center, right, justify, and char. When supported, the char value aligns the textual content on the character defined in the char attribute and on offset defined by the charoff attribute. Note that this attribute overrides the specified align of its &lt;colgroup&gt; parent element. Use the text-align CSS property on the &lt;td&gt; and &lt;th&gt; elements instead, as this attribute is deprecated.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Col Align(string value)
	{
		return this.Attribute("align", value);
	}

	/// <summary>
	/// Defines the background color of each column cell. The value is an HTML color; either a 6-digit hexadecimal RGB code, prefixed by a #, or a color keyword. Other CSS &lt;color&gt; values are not supported. Use the background-color CSS property instead, as this attribute is deprecated.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Col Bgcolor(string value)
	{
		return this.Attribute("bgcolor", value);
	}

	/// <summary>
	/// Does nothing. It was originally intended to specify the alignment of the content to a character of each column cell. Typical values for this include a period (. ) when attempting to align numbers or monetary values. If align is not set to char, this attribute is ignored, though it will still override the specified char of its &lt;colgroup&gt; parent element.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Col Char(string value)
	{
		return this.Attribute("char", value);
	}

	/// <summary>
	/// Does nothing. It was originally intended to specify the number of characters to offset the column cell content from the alignment character specified by the char attribute.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Col Charoff(string value)
	{
		return this.Attribute("charoff", value);
	}

	/// <summary>
	/// Specifies the number of consecutive columns the &lt;col&gt; element spans. The value must be a positive integer greater than zero. If not present, its default value is 1.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Col Span(string value)
	{
		return this.Attribute("span", value);
	}

	/// <summary>
	/// Specifies the vertical alignment of each column cell. The possible enumerated values are baseline, bottom, middle, and top. Note that this attribute overrides the specified valign of its &lt;colgroup&gt; parent element. Use the vertical-align CSS property on the &lt;td&gt; and &lt;th&gt; elements instead, as this attribute is deprecated.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Col Valign(string value)
	{
		return this.Attribute("valign", value);
	}

	/// <summary>
	/// Specifies a default width for each column. In addition to the standard pixel and percentage values, this attribute can take the special form 0*, which means that the width of each column spanned should be the minimum width necessary to hold the column&apos;s contents. Relative widths such as 5* can also be used. Note that this attribute overrides the specified width of its &lt;colgroup&gt; parent element. Use the width CSS property instead, as this attribute is deprecated.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/col
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Col Width(string value)
	{
		return this.Attribute("width", value);
	}

}
