// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;

/// <summary>
/// The <data> HTML element links a given piece of content with a machine-readable translation. If the content is time- or date-related, the <time> element must be used.
/// </summary>
public partial class Data(IHtmlContent content)
	: HtmlTag("data", false, content)
{
	/// <summary>
	/// This attribute specifies the machine-readable translation of the content of the element.
	/// </summary>
	public Data Value(string value)
	{
		return this.Attribute("value", value);
	}

}
