// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/data

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;data&gt; HTML element links a given piece of content with a machine-readable translation. If the content is time- or date-related, the &lt;time&gt; element must be used.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/data
/// </summary>
public partial class Data
	: HtmlTag
{
	/// <summary>
	/// The &lt;data&gt; HTML element links a given piece of content with a machine-readable translation. If the content is time- or date-related, the &lt;time&gt; element must be used.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/data
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Data(params IEnumerable<IHtmlContent> contents)
		: base("data", false, contents)
	{
	}

	/// <summary>
	/// The &lt;data&gt; HTML element links a given piece of content with a machine-readable translation. If the content is time- or date-related, the &lt;time&gt; element must be used.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/data
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Data(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// This attribute specifies the machine-readable translation of the content of the element.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/data
	/// </summary>
	public Data Value(string value)
	{
		return this.Attribute("value", value);
	}

}
