// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/del

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;del&gt; HTML element represents a range of text that has been deleted from a document. This can be used when rendering &quot;track changes&quot; or source code diff information, for example. The &lt;ins&gt; element can be used for the opposite purpose: to indicate text that has been added to the document.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/del
/// </summary>
public partial class Del
	: HtmlTag
{
	/// <summary>
	/// The &lt;del&gt; HTML element represents a range of text that has been deleted from a document. This can be used when rendering &quot;track changes&quot; or source code diff information, for example. The &lt;ins&gt; element can be used for the opposite purpose: to indicate text that has been added to the document.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/del
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Del(params IEnumerable<IHtmlContent> contents)
		: base("del", false, contents)
	{
	}

	/// <summary>
	/// The &lt;del&gt; HTML element represents a range of text that has been deleted from a document. This can be used when rendering &quot;track changes&quot; or source code diff information, for example. The &lt;ins&gt; element can be used for the opposite purpose: to indicate text that has been added to the document.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/del
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Del(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// A URI for a resource that explains the change (for example, meeting minutes).
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/del
	/// </summary>
	public Del Cite(string value)
	{
		return this.Attribute("cite", value);
	}

	/// <summary>
	/// This attribute indicates the time and date of the change and must be a valid date string with an optional time. If the value cannot be parsed as a date with an optional time string, the element does not have an associated timestamp. For the format of the string without a time, see Date strings. The format of the string if it includes both date and time is covered in Local date and time strings.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/del
	/// </summary>
	public Del Datetime(string value)
	{
		return this.Attribute("datetime", value);
	}

}
