// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The <del> HTML element represents a range of text that has been deleted from a document. This can be used when rendering "track changes" or source code diff information, for example. The <ins> element can be used for the opposite purpose: to indicate text that has been added to the document.
/// </summary>
public partial class Del(params IEnumerable<IHtmlContent> contents)
	: HtmlTag("del", false, contents)
{
	public Del(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// A URI for a resource that explains the change (for example, meeting minutes).
	/// </summary>
	public Del Cite(string value)
	{
		return this.Attribute("cite", value);
	}

	/// <summary>
	/// This attribute indicates the time and date of the change and must be a valid date string with an optional time. If the value cannot be parsed as a date with an optional time string, the element does not have an associated timestamp. For the format of the string without a time, see Date strings. The format of the string if it includes both date and time is covered in Local date and time strings.
	/// </summary>
	public Del Datetime(string value)
	{
		return this.Attribute("datetime", value);
	}

}
