// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;

/// <summary>
/// The <dialog> HTML element represents a modal or non-modal dialog box or other interactive component, such as a dismissible alert, inspector, or subwindow. The HTML <dialog> element is used to create both modal and non-modal dialog boxes. Modal dialog boxes interrupt interaction with the rest of the page being inert, while non-modal dialog boxes allow interaction with the rest of the page. JavaScript should be used to display the <dialog> element. Use the.showModal() method to display a modal dialog and the.show() method to display a non-modal dialog. The dialog box can be closed using the.close() method or using the dialog method when submitting a <form> that is nested within the <dialog> element. Modal dialogs can also be closed by pressing the Esc key.
/// </summary>
public partial class Dialog(IHtmlContent content)
	: HtmlTag("dialog", false, content)
{
	/// <summary>
	/// The dialog can be dismissed using any of the three methods.
	/// </summary>
	public Dialog Any(string value)
	{
		return this.Attribute("any", value);
	}

	/// <summary>
	/// Specifies the types of user actions that can be used to close the <dialog> element. This attribute distinguishes three methods by which a dialog might be closed:
	/// </summary>
	public Dialog Closedby(string value)
	{
		return this.Attribute("closedby", value);
	}

	/// <summary>
	/// The dialog can be dismissed with a platform-specific user action or a developer-specified mechanism.
	/// </summary>
	public Dialog Closerequest(string value)
	{
		return this.Attribute("closerequest", value);
	}

	/// <summary>
	/// Add display to the transitions list so that the <dialog> will remain as display: block (or another visible display value set on the dialog's open state) for the duration of the transition, ensuring the other transitions are visible.
	/// </summary>
	public Dialog Display(string value)
	{
		return this.Attribute("display", value);
	}

	/// <summary>
	/// The dialog can only be dismissed with a developer-specified mechanism.
	/// </summary>
	public Dialog None(string value)
	{
		return this.Attribute("none", value);
	}

	/// <summary>
	/// Indicates that the dialog box is active and is available for interaction. If the open attribute is not set, the dialog box will not be visible to the user.
	/// It is recommended to use the.show() or.showModal() method to render dialogs, rather than the open attribute. If a <dialog> is opened using the open attribute, it is non-modal.
	/// </summary>
	public Dialog Open(string value)
	{
		return this.Attribute("open", value);
	}

	/// <summary>
	/// Include overlay in the transitions list to ensure the removal of the <dialog> from the top layer is deferred until the transition completes, again ensuring the transition is visible.
	/// </summary>
	public Dialog Overlay(string value)
	{
		return this.Attribute("overlay", value);
	}

	/// <summary>
	/// Provides a set of starting values for properties set on the <dialog> that you want to transition from every time it is opened. This is needed to avoid unexpected behavior. By default, CSS transitions only occur when a property changes from one value to another on a visible element; they are not triggered on elements' first style updates, or when the display type changes from none to another type.
	/// </summary>
	public Dialog StartingStyle(string value)
	{
		return this.Attribute("starting-style", value);
	}

	/// <summary>
	/// Set transition-behavior: allow-discrete on the display and overlay transitions (or on the transition shorthand) to enable discrete transitions on these two properties that are not by default animatable.
	/// </summary>
	public Dialog TransitionBehavior(string value)
	{
		return this.Attribute("transition-behavior", value);
	}

}
