// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;

/// <summary>
/// The <embed> HTML element embeds external content at the specified point in the document. This content is provided by an external application or other source of interactive content such as a browser plug-in.
/// </summary>
public partial class Embed(IHtmlContent content)
	: HtmlTag("embed", false, content)
{
	/// <summary>
	/// The displayed height of the resource, in CSS pixels. This must be an absolute value; percentages are not allowed.
	/// </summary>
	public Embed Height(string value)
	{
		return this.Attribute("height", value);
	}

	/// <summary>
	/// The URL of the resource being embedded.
	/// </summary>
	public Embed Src(string value)
	{
		return this.Attribute("src", value);
	}

	/// <summary>
	/// The MIME type to use to select the plug-in to instantiate.
	/// </summary>
	public Embed Type(string value)
	{
		return this.Attribute("type", value);
	}

	/// <summary>
	/// The displayed width of the resource, in CSS pixels. This must be an absolute value; percentages are not allowed.
	/// </summary>
	public Embed Width(string value)
	{
		return this.Attribute("width", value);
	}

}
