// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;fieldset&gt; HTML element is used to group several controls as well as labels ( &lt;label&gt; ) within a web form.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset
/// </summary>
public partial class Fieldset
	: HtmlTag
{
	/// <summary>
	/// The &lt;fieldset&gt; HTML element is used to group several controls as well as labels ( &lt;label&gt; ) within a web form.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Fieldset(params IEnumerable<IHtmlContent> contents)
		: base("fieldset", false, contents)
	{
	}

	/// <summary>
	/// The &lt;fieldset&gt; HTML element is used to group several controls as well as labels ( &lt;label&gt; ) within a web form.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Fieldset(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// If this Boolean attribute is set, all form controls that are descendants of the &lt;fieldset&gt;, are disabled, meaning they are not editable and won&apos;t be submitted along with the &lt;form&gt;. They won&apos;t receive any browsing events, like mouse clicks or focus-related events. By default browsers display such controls grayed out. Note that form elements inside the &lt;legend&gt; element won&apos;t be disabled.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset
	/// </summary>
	public Fieldset Disabled(string value)
	{
		return this.Attribute("disabled", value);
	}

	/// <summary>
	/// This attribute takes the value of the id attribute of a &lt;form&gt; element you want the &lt;fieldset&gt; to be part of, even if it is not inside the form. Please note that usage of this is confusing â if you want the &lt;input&gt; elements inside the &lt;fieldset&gt; to be associated with the form, you need to use the form attribute directly on those elements. You can check which elements are associated with a form via JavaScript, using HTMLFormElement.elements.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset
	/// </summary>
	public Fieldset Form(string value)
	{
		return this.Attribute("form", value);
	}

	/// <summary>
	/// The name associated with the group.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset
	/// </summary>
	public Fieldset Name(string value)
	{
		return this.Attribute("name", value);
	}

}
