// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;

/// <summary>
/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The <font> HTML element defines the font size, color and face for its content. Warning: 
/// Do not use this element. Use the CSS Fonts properties to style text.
/// </summary>
public partial class Font(IHtmlContent content)
	: HtmlTag("font", false, content)
{
	/// <summary>
	/// This attribute sets the text color using either a named color or a color specified in the hexadecimal #RRGGBB format.
	/// </summary>
	public Font Color(string value)
	{
		return this.Attribute("color", value);
	}

	/// <summary>
	/// This attribute contains a comma-separated list of one or more font names. The document text in the default style is rendered in the first font face that the client's browser supports. If no font listed is installed on the local system, the browser typically defaults to the proportional or fixed-width font for that system.
	/// </summary>
	public Font Face(string value)
	{
		return this.Attribute("face", value);
	}

	/// <summary>
	/// This attribute specifies the font size as either a numeric or relative value. Numeric values range from 1 to 7 with 1 being the smallest and 3 the default. It can be defined using a relative value, like +2 or -3, which sets it relative to 3, the default value.
	/// </summary>
	public Font Size(string value)
	{
		return this.Attribute("size", value);
	}

}
