// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/font
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;font&gt; HTML element defines the font size, color and face for its content. Warning: 
/// Do not use this element. Use the CSS Fonts properties to style text.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/font
///<br/> - by Mozilla Contributors
/// </summary>
[Obsolete]
public partial class Font
	: HtmlTag
{
	/// <summary>
	/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;font&gt; HTML element defines the font size, color and face for its content. Warning: 
	/// Do not use this element. Use the CSS Fonts properties to style text.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/font
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Font(params IEnumerable<IHtmlContent> contents)
		: base("font", false, contents)
	{
	}

	/// <summary>
	/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;font&gt; HTML element defines the font size, color and face for its content. Warning: 
	/// Do not use this element. Use the CSS Fonts properties to style text.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/font
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Font(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// This attribute sets the text color using either a named color or a color specified in the hexadecimal #RRGGBB format.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/font
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Font Color(string value)
	{
		return this.Attribute("color", value);
	}

	/// <summary>
	/// This attribute contains a comma-separated list of one or more font names. The document text in the default style is rendered in the first font face that the client&apos;s browser supports. If no font listed is installed on the local system, the browser typically defaults to the proportional or fixed-width font for that system.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/font
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Font Face(string value)
	{
		return this.Attribute("face", value);
	}

	/// <summary>
	/// This attribute specifies the font size as either a numeric or relative value. Numeric values range from 1 to 7 with 1 being the smallest and 3 the default. It can be defined using a relative value, like +2 or -3, which sets it relative to 3, the default value.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/font
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Font Size(string value)
	{
		return this.Attribute("size", value);
	}

}
