// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;

/// <summary>
/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The <frameset> HTML element is used to contain <frame> elements. Note: 
/// Because the use of frames is now discouraged in favor of using <iframe>, this element is not typically used by modern websites.
/// </summary>
public partial class Frameset(IHtmlContent content)
	: HtmlTag("frameset", false, content)
{
	/// <summary>
	/// This attribute specifies the number and size of horizontal spaces in a frameset.
	/// </summary>
	public Frameset Cols(string value)
	{
		return this.Attribute("cols", value);
	}

	/// <summary>
	/// This attribute specifies the number and size of vertical spaces in a frameset.
	/// </summary>
	public Frameset Rows(string value)
	{
		return this.Attribute("rows", value);
	}

}
