// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/frameset

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;frameset&gt; HTML element is used to contain &lt;frame&gt; elements. Note: 
/// Because the use of frames is now discouraged in favor of using &lt;iframe&gt;, this element is not typically used by modern websites.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/frameset
/// </summary>
[Obsolete]
public partial class Frameset
	: HtmlTag
{
	/// <summary>
	/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;frameset&gt; HTML element is used to contain &lt;frame&gt; elements. Note: 
	/// Because the use of frames is now discouraged in favor of using &lt;iframe&gt;, this element is not typically used by modern websites.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/frameset
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Frameset(params IEnumerable<IHtmlContent> contents)
		: base("frameset", false, contents)
	{
	}

	/// <summary>
	/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;frameset&gt; HTML element is used to contain &lt;frame&gt; elements. Note: 
	/// Because the use of frames is now discouraged in favor of using &lt;iframe&gt;, this element is not typically used by modern websites.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/frameset
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Frameset(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// This attribute specifies the number and size of horizontal spaces in a frameset.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/frameset
	/// </summary>
	[Obsolete]
	public Frameset Cols(string value)
	{
		return this.Attribute("cols", value);
	}

	/// <summary>
	/// This attribute specifies the number and size of vertical spaces in a frameset.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/frameset
	/// </summary>
	[Obsolete]
	public Frameset Rows(string value)
	{
		return this.Attribute("rows", value);
	}

}
