// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/header
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;header&gt; HTML element represents introductory content, typically a group of introductory or navigational aids. It may contain some heading elements but also a logo, a search form, an author name, and other elements.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/header
///<br/> - by Mozilla Contributors
/// </summary>
public partial class Header
	: HtmlTag
{
	/// <summary>
	/// The &lt;header&gt; HTML element represents introductory content, typically a group of introductory or navigational aids. It may contain some heading elements but also a logo, a search form, an author name, and other elements.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/header
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Header(params IEnumerable<IHtmlContent> contents)
		: base("header", false, contents)
	{
	}

	/// <summary>
	/// The &lt;header&gt; HTML element represents introductory content, typically a group of introductory or navigational aids. It may contain some heading elements but also a logo, a search form, an author name, and other elements.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/header
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Header(string text)
		: this(Encode(text))
	{
	}
}
