// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The <head> HTML element contains machine-readable information ( metadata ) about the document, like its title, scripts, and style sheets. There can be only one <head> element in an HTML document. Note: <head> primarily holds information for machine processing, not human-readability. For human-visible information, like top-level headings and listed authors, see the <header> element.
/// </summary>
public partial class Head(params IEnumerable<IHtmlContent> contents)
	: HtmlTag("head", false, contents)
{
	public Head(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// The URI s of one or more metadata profiles, separated by white space.
	/// </summary>
	[Obsolete]
	public Head Profile(string value)
	{
		return this.Attribute("profile", value);
	}

}
