// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hgroup

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;hgroup&gt; HTML element represents a heading and related content. It groups a single &lt;h1&gt;â&lt;h6&gt; element with one or more &lt;p&gt;.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hgroup
/// </summary>
public partial class Hgroup
	: HtmlTag
{
	/// <summary>
	/// The &lt;hgroup&gt; HTML element represents a heading and related content. It groups a single &lt;h1&gt;â&lt;h6&gt; element with one or more &lt;p&gt;.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hgroup
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Hgroup(params IEnumerable<IHtmlContent> contents)
		: base("hgroup", false, contents)
	{
	}

	/// <summary>
	/// The &lt;hgroup&gt; HTML element represents a heading and related content. It groups a single &lt;h1&gt;â&lt;h6&gt; element with one or more &lt;p&gt;.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hgroup
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Hgroup(string text)
		: this(Encode(text))
	{
	}
}
