// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hr

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;hr&gt; HTML element represents a thematic break between paragraph-level elements: for example, a change of scene in a story, or a shift of topic within a section.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hr
/// </summary>
public partial class Hr
	: HtmlTag
{
	/// <summary>
	/// The &lt;hr&gt; HTML element represents a thematic break between paragraph-level elements: for example, a change of scene in a story, or a shift of topic within a section.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hr
	/// </summary>
	public Hr()
		: base("hr", true)
	{
	}
	/// <summary>
	/// Sets the alignment of the rule on the page. If no value is specified, the default value is left.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hr
	/// </summary>
	[Obsolete]
	public Hr Align(string value)
	{
		return this.Attribute("align", value);
	}

	/// <summary>
	/// Sets the color of the rule through color name or hexadecimal value.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hr
	/// </summary>
	[Obsolete]
	public Hr Color(string value)
	{
		return this.Attribute("color", value);
	}

	/// <summary>
	/// Sets the rule to have no shading.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hr
	/// </summary>
	[Obsolete]
	public Hr Noshade(string value)
	{
		return this.Attribute("noshade", value);
	}

	/// <summary>
	/// Sets the height, in pixels, of the rule.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hr
	/// </summary>
	[Obsolete]
	public Hr Size(string value)
	{
		return this.Attribute("size", value);
	}

	/// <summary>
	/// Sets the length of the rule on the page through a pixel or percentage value.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/hr
	/// </summary>
	[Obsolete]
	public Hr Width(string value)
	{
		return this.Attribute("width", value);
	}

}
