// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
///The &lt;hr&gt; HTML element represents a thematic break between paragraph-level elements: for example, a change of scene in a story, or a shift of topic within a section.
/// </summary>
public partial class Hr
	: HtmlTag
{
	/// <summary>
	///The &lt;hr&gt; HTML element represents a thematic break between paragraph-level elements: for example, a change of scene in a story, or a shift of topic within a section.
	/// </summary>
	public Hr()
		: base("hr", true)
	{
	}
	/// <summary>
	///Sets the alignment of the rule on the page. If no value is specified, the default value is left.
	/// </summary>
	[Obsolete]
	public Hr Align(string value)
	{
		return this.Attribute("align", value);
	}

	/// <summary>
	///Sets the color of the rule through color name or hexadecimal value.
	/// </summary>
	[Obsolete]
	public Hr Color(string value)
	{
		return this.Attribute("color", value);
	}

	/// <summary>
	///Sets the rule to have no shading.
	/// </summary>
	[Obsolete]
	public Hr Noshade(string value)
	{
		return this.Attribute("noshade", value);
	}

	/// <summary>
	///Sets the height, in pixels, of the rule.
	/// </summary>
	[Obsolete]
	public Hr Size(string value)
	{
		return this.Attribute("size", value);
	}

	/// <summary>
	///Sets the length of the rule on the page through a pixel or percentage value.
	/// </summary>
	[Obsolete]
	public Hr Width(string value)
	{
		return this.Attribute("width", value);
	}

}
