// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The <iframe> HTML element represents a nested browsing context, embedding another HTML page into the current one.
/// </summary>
public partial class Iframe(params IEnumerable<IHtmlContent> contents)
	: HtmlTag("iframe", false, contents)
{
	public Iframe(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// The alignment of this element with respect to the surrounding context.
	/// </summary>
	public Iframe Align(string value)
	{
		return this.Attribute("align", value);
	}

	/// <summary>
	/// Specifies a Permissions Policy for the <iframe>. The policy defines what features are available to the <iframe> (for example, access to the microphone, camera, battery, web-share, etc.) based on the origin of the request.
	/// </summary>
	public Iframe Allow(string value)
	{
		return this.Attribute("allow", value);
	}

	/// <summary>
	/// Allows downloading files through an <a> or <area> element with the download attribute, as well as through the navigation that leads to a download of a file. This works regardless of whether the user clicked on the link, or JS code initiated it without user interaction.
	/// </summary>
	public Iframe AllowDownloads(string value)
	{
		return this.Attribute("allow-downloads", value);
	}

	/// <summary>
	/// Allows the page to submit forms. If this keyword is not used, a form will be displayed as normal, but submitting it will not trigger input validation, send data to a web server, or close a dialog.
	/// </summary>
	public Iframe AllowForms(string value)
	{
		return this.Attribute("allow-forms", value);
	}

	/// <summary>
	/// Allows the page to open modal windows by Window.alert(), Window.confirm(), Window.print() and Window.prompt(), while opening a <dialog> is allowed regardless of this keyword. It also allows the page to receive BeforeUnloadEvent event.
	/// </summary>
	public Iframe AllowModals(string value)
	{
		return this.Attribute("allow-modals", value);
	}

	/// <summary>
	/// Lets the resource lock the screen orientation.
	/// </summary>
	public Iframe AllowOrientationLock(string value)
	{
		return this.Attribute("allow-orientation-lock", value);
	}

	/// <summary>
	/// Allows the page to use the Pointer Lock API.
	/// </summary>
	public Iframe AllowPointerLock(string value)
	{
		return this.Attribute("allow-pointer-lock", value);
	}

	/// <summary>
	/// Allows popups (created, for example, by Window.open() or target="_blank" ). If this keyword is not used, such functionality will silently fail.
	/// </summary>
	public Iframe AllowPopups(string value)
	{
		return this.Attribute("allow-popups", value);
	}

	/// <summary>
	/// Allows a sandboxed document to open a new browsing context without forcing the sandboxing flags upon it. This will allow, for example, a third-party advertisement to be safely sandboxed without forcing the same restrictions upon the page the ad links to. If this flag is not included, a redirected page, popup window, or new tab will be subject to the same sandbox restrictions as the originating <iframe>.
	/// </summary>
	public Iframe AllowPopupsToEscapeSandbox(string value)
	{
		return this.Attribute("allow-popups-to-escape-sandbox", value);
	}

	/// <summary>
	/// Allows embedders to have control over whether an iframe can start a presentation session.
	/// </summary>
	public Iframe AllowPresentation(string value)
	{
		return this.Attribute("allow-presentation", value);
	}

	/// <summary>
	/// If this token is not used, the resource is treated as being from a special origin that always fails the same-origin policy (potentially preventing access to data storage/cookies and some JavaScript APIs).
	/// </summary>
	public Iframe AllowSameOrigin(string value)
	{
		return this.Attribute("allow-same-origin", value);
	}

	/// <summary>
	/// Allows the page to run scripts (but not create pop-up windows). If this keyword is not used, this operation is not allowed.
	/// </summary>
	public Iframe AllowScripts(string value)
	{
		return this.Attribute("allow-scripts", value);
	}

	/// <summary>
	/// Allows a document loaded in the <iframe> to use the Storage Access API to request access to unpartitioned cookies.
	/// </summary>
	public Iframe AllowStorageAccessByUserActivation(string value)
	{
		return this.Attribute("allow-storage-access-by-user-activation", value);
	}

	/// <summary>
	/// Lets the resource navigate the top-level browsing context (the one named _top ).
	/// </summary>
	public Iframe AllowTopNavigation(string value)
	{
		return this.Attribute("allow-top-navigation", value);
	}

	/// <summary>
	/// Lets the resource navigate the top-level browsing context, but only if initiated by a user gesture.
	/// </summary>
	public Iframe AllowTopNavigationByUserActivation(string value)
	{
		return this.Attribute("allow-top-navigation-by-user-activation", value);
	}

	/// <summary>
	/// Allows navigations to non- http protocols built into browser or registered by a website. This feature is also activated by allow-popups or allow-top-navigation keyword.
	/// </summary>
	public Iframe AllowTopNavigationToCustomProtocols(string value)
	{
		return this.Attribute("allow-top-navigation-to-custom-protocols", value);
	}

	/// <summary>
	/// Set to true if the <iframe> can activate fullscreen mode by calling the requestFullscreen() method.
	/// </summary>
	public Iframe Allowfullscreen(string value)
	{
		return this.Attribute("allowfullscreen", value);
	}

	/// <summary>
	/// Set to true if a cross-origin <iframe> should be allowed to invoke the Payment Request API.
	/// </summary>
	public Iframe Allowpaymentrequest(string value)
	{
		return this.Attribute("allowpaymentrequest", value);
	}

	/// <summary>
	/// Only when the frame's content is larger than its dimensions.
	/// </summary>
	public Iframe Auto(string value)
	{
		return this.Attribute("auto", value);
	}

	/// <summary>
	/// A boolean attribute that, if present, specifies that the selected topics for the current user should be sent with the request for the <iframe> 's source. See Using the Topics API for more details.
	/// </summary>
	public Iframe Browsingtopics(string value)
	{
		return this.Attribute("browsingtopics", value);
	}

	/// <summary>
	/// Set to true to make the <iframe> credentialless, meaning that its content will be loaded in a new, ephemeral context. It doesn't have access to the network, cookies, and storage data associated with its origin. It uses a new context local to the top-level document lifetime. In return, the Cross-Origin-Embedder-Policy (COEP) embedding rules can be lifted, so documents with COEP set can embed third-party documents that do not. See IFrame credentialless for more details.
	/// </summary>
	public Iframe Credentialless(string value)
	{
		return this.Attribute("credentialless", value);
	}

	/// <summary>
	/// A Content Security Policy enforced for the embedded resource. See HTMLIFrameElement.csp for details.
	/// </summary>
	public Iframe Csp(string value)
	{
		return this.Attribute("csp", value);
	}

	/// <summary>
	/// Load the iframe immediately on page load (this is the default value).
	/// </summary>
	public Iframe Eager(string value)
	{
		return this.Attribute("eager", value);
	}

	/// <summary>
	/// The value 1 (the default) draws a border around this frame. The value 0 removes the border around this frame, but you should instead use the CSS property border to control <iframe> borders.
	/// </summary>
	public Iframe Frameborder(string value)
	{
		return this.Attribute("frameborder", value);
	}

	/// <summary>
	/// The height of the frame in CSS pixels. Default is 150.
	/// </summary>
	public Iframe Height(string value)
	{
		return this.Attribute("height", value);
	}

	/// <summary>
	/// Defer loading of the iframe until it reaches a calculated distance from the visual viewport, as defined by the browser.
	/// The intent is to avoid using the network and storage bandwidth required to fetch the frame until the browser is reasonably certain that it will be needed.
	/// This improves the performance and cost in most typical use cases, in particular by reducing initial page load times.
	/// </summary>
	public Iframe Lazy(string value)
	{
		return this.Attribute("lazy", value);
	}

	/// <summary>
	/// Indicates when the browser should load the iframe:
	/// </summary>
	public Iframe Loading(string value)
	{
		return this.Attribute("loading", value);
	}

	/// <summary>
	/// A URL of a long description of the frame's content. Due to widespread misuse, this is not helpful for non-visual browsers.
	/// </summary>
	public Iframe Longdesc(string value)
	{
		return this.Attribute("longdesc", value);
	}

	/// <summary>
	/// The amount of space in pixels between the frame's content and its top and bottom borders.
	/// </summary>
	public Iframe Marginheight(string value)
	{
		return this.Attribute("marginheight", value);
	}

	/// <summary>
	/// The amount of space in pixels between the frame's content and its left and right borders.
	/// </summary>
	public Iframe Marginwidth(string value)
	{
		return this.Attribute("marginwidth", value);
	}

	/// <summary>
	/// A targetable name for the embedded browsing context. This can be used in the target attribute of the <a>, <form>, or <base> elements; the formtarget attribute of the <input> or <button> elements; or the windowName parameter in the window.open() method. In addition, the name becomes a property of the Window and Document objects, containing a reference to the embedded window or the element itself.
	/// </summary>
	public Iframe Name(string value)
	{
		return this.Attribute("name", value);
	}

	/// <summary>
	/// Never show a scrollbar.
	/// </summary>
	public Iframe No(string value)
	{
		return this.Attribute("no", value);
	}

	/// <summary>
	/// The Referer header will not be sent.
	/// </summary>
	public Iframe NoReferrer(string value)
	{
		return this.Attribute("no-referrer", value);
	}

	/// <summary>
	/// The Referer header will not be sent to origin s without TLS ( HTTPS ).
	/// </summary>
	public Iframe NoReferrerWhenDowngrade(string value)
	{
		return this.Attribute("no-referrer-when-downgrade", value);
	}

	/// <summary>
	/// The sent referrer will be limited to the origin of the referring page: its scheme, host, and port.
	/// </summary>
	public Iframe Origin(string value)
	{
		return this.Attribute("origin", value);
	}

	/// <summary>
	/// The referrer sent to other origins will be limited to the scheme, the host, and the port. Navigations on the same origin will still include the path.
	/// </summary>
	public Iframe OriginWhenCrossOrigin(string value)
	{
		return this.Attribute("origin-when-cross-origin", value);
	}

	/// <summary>
	/// Contains a string representation of an options object representing a private state token operation; this object has the same structure as the RequestInit dictionary's privateToken property. IFrames containing this attribute can initiate operations such as issuing or redeeming tokens when their embedded content is loaded.
	/// </summary>
	public Iframe Privatetoken(string value)
	{
		return this.Attribute("privatetoken", value);
	}

	/// <summary>
	/// Indicates which referrer to send when fetching the frame's resource:
	/// </summary>
	public Iframe Referrerpolicy(string value)
	{
		return this.Attribute("referrerpolicy", value);
	}

	/// <summary>
	/// A referrer will be sent for same origin, but cross-origin requests will contain no referrer information.
	/// </summary>
	public Iframe SameOrigin(string value)
	{
		return this.Attribute("same-origin", value);
	}

	/// <summary>
	/// Controls the restrictions applied to the content embedded in the <iframe>. The value of the attribute can either be empty to apply all restrictions, or space-separated tokens to lift particular restrictions:
	/// </summary>
	public Iframe Sandbox(string value)
	{
		return this.Attribute("sandbox", value);
	}

	/// <summary>
	/// Indicates when the browser should provide a scrollbar for the frame:
	/// </summary>
	public Iframe Scrolling(string value)
	{
		return this.Attribute("scrolling", value);
	}

	/// <summary>
	/// The URL of the page to embed. Use a value of about:blank to embed an empty page that conforms to the same-origin policy. Also note that programmatically removing an <iframe> 's src attribute (e.g., via Element.removeAttribute() ) causes about:blank to be loaded in the frame in Firefox (from version 65), Chromium-based browsers, and Safari/iOS.
	/// </summary>
	public Iframe Src(string value)
	{
		return this.Attribute("src", value);
	}

	/// <summary>
	/// Inline HTML to embed, overriding the src attribute. Its content should follow the syntax of a full HTML document, which includes the doctype directive, <html>, <body> tags, etc., although most of them can be omitted, leaving only the body content. This doc will have about:srcdoc as its location. If a browser does not support the srcdoc attribute, it will fall back to the URL in the src attribute.
	/// </summary>
	public Iframe Srcdoc(string value)
	{
		return this.Attribute("srcdoc", value);
	}

	/// <summary>
	/// Only send the origin of the document as the referrer when the protocol security level stays the same (HTTPSâHTTPS), but don't send it to a less secure destination (HTTPSâHTTP).
	/// </summary>
	public Iframe StrictOrigin(string value)
	{
		return this.Attribute("strict-origin", value);
	}

	/// <summary>
	/// Send a full URL when performing a same-origin request, only send the origin when the protocol security level stays the same (HTTPSâHTTPS), and send no header to a less secure destination (HTTPSâHTTP).
	/// </summary>
	public Iframe StrictOriginWhenCrossOrigin(string value)
	{
		return this.Attribute("strict-origin-when-cross-origin", value);
	}

	/// <summary>
	/// The referrer will include the origin and the path (but not the fragment, password, or username ). This value is unsafe, because it leaks origins and paths from TLS-protected resources to insecure origins.
	/// </summary>
	public Iframe UnsafeUrl(string value)
	{
		return this.Attribute("unsafe-url", value);
	}

	/// <summary>
	/// The width of the frame in CSS pixels. Default is 300.
	/// </summary>
	public Iframe Width(string value)
	{
		return this.Attribute("width", value);
	}

	/// <summary>
	/// Always show a scrollbar.
	/// </summary>
	public Iframe Yes(string value)
	{
		return this.Attribute("yes", value);
	}

}
