// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;img&gt; HTML element embeds an image into the document.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
/// </summary>
public partial class Img
	: HtmlTag
{
	/// <summary>
	/// The &lt;img&gt; HTML element embeds an image into the document.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img()
		: base("img", true)
	{
	}
	/// <summary>
	/// Aligns the image with its surrounding context. Use the float and/or vertical-align CSS properties instead of this attribute. Allowed values:
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	[Obsolete]
	public Img Align(string value)
	{
		return this.Attribute("align", value);
	}

	/// <summary>
	/// Defines text that can replace the image in the page.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Alt(string value)
	{
		return this.Attribute("alt", value);
	}

	/// <summary>
	/// A CORS request is sent with credentials omitted (that is, no cookies, X.509 certificates, or Authorization request header).
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Anonymous(string value)
	{
		return this.Attribute("anonymous", value);
	}

	/// <summary>
	/// Decode the image asynchronously, after rendering and presenting the other DOM content.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Async(string value)
	{
		return this.Attribute("async", value);
	}

	/// <summary>
	/// Specifies that you want the browser to send an Attribution-Reporting-Eligible header along with the image request.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	[Obsolete]
	public Img Attributionsrc(string value)
	{
		return this.Attribute("attributionsrc", value);
	}

	/// <summary>
	/// No preference for the decoding mode; the browser decides what is best for the user. This is the default value.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Auto(string value)
	{
		return this.Attribute("auto", value);
	}

	/// <summary>
	/// Don&apos;t set a preference for the fetch priority.
	/// This is the default.
	/// It is used if no value or an invalid value is set.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Auto2(string value)
	{
		return this.Attribute("auto_2", value);
	}

	/// <summary>
	/// The width of a border around the image. Use the border CSS property instead.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	[Obsolete]
	public Img Border(string value)
	{
		return this.Attribute("border", value);
	}

	/// <summary>
	/// The default, equivalent to vertical-align: unset or vertical-align: initial
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Bottom(string value)
	{
		return this.Attribute("bottom", value);
	}

	/// <summary>
	/// Indicates if the fetching of the image must be done using a CORS request. Image data from a CORS-enabled image returned from a CORS request can be reused in the &lt;canvas&gt; element without being marked &quot; tainted &quot;.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Crossorigin(string value)
	{
		return this.Attribute("crossorigin", value);
	}

	/// <summary>
	/// This attribute provides a hint to the browser as to whether it should perform image decoding along with rendering the other DOM content in a single presentation step that looks more &quot;correct&quot; ( sync ), or render and present the other DOM content first and then decode the image and present it later ( async ). In practice, async means that the next paint does not wait for the image to decode.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Decoding(string value)
	{
		return this.Attribute("decoding", value);
	}

	/// <summary>
	/// Loads the image immediately, regardless of whether or not the image is currently within the visible viewport (this is the default value).
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Eager(string value)
	{
		return this.Attribute("eager", value);
	}

	/// <summary>
	/// Marks the image for observation by the PerformanceElementTiming API. The value given becomes an identifier for the observed image element. See also the elementtiming attribute page.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Elementtiming(string value)
	{
		return this.Attribute("elementtiming", value);
	}

	/// <summary>
	/// Provides a hint of the relative priority to use when fetching the image. Allowed values:
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Fetchpriority(string value)
	{
		return this.Attribute("fetchpriority", value);
	}

	/// <summary>
	/// The intrinsic height of the image, in pixels. Must be an integer without a unit.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Height(string value)
	{
		return this.Attribute("height", value);
	}

	/// <summary>
	/// Fetch the image at a high priority relative to other images.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img High(string value)
	{
		return this.Attribute("high", value);
	}

	/// <summary>
	/// The number of pixels of white space on the left and right of the image. Use the margin CSS property instead.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	[Obsolete]
	public Img Hspace(string value)
	{
		return this.Attribute("hspace", value);
	}

	/// <summary>
	/// This Boolean attribute indicates that the image is part of a server-side map. If so, the coordinates where the user clicked on the image are sent to the server.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Ismap(string value)
	{
		return this.Attribute("ismap", value);
	}

	/// <summary>
	/// Defers loading the image until it reaches a calculated distance from the viewport, as defined by the browser. The intent is to avoid the network and storage bandwidth needed to handle the image until it&apos;s reasonably certain that it will be needed. This generally improves the performance of the content in most typical use cases.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Lazy(string value)
	{
		return this.Attribute("lazy", value);
	}

	/// <summary>
	/// Equivalent to float: left
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Left(string value)
	{
		return this.Attribute("left", value);
	}

	/// <summary>
	/// Indicates how the browser should load the image:
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Loading(string value)
	{
		return this.Attribute("loading", value);
	}

	/// <summary>
	/// A link to a more detailed description of the image. Possible values are a URL or an element id.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	[Obsolete]
	public Img Longdesc(string value)
	{
		return this.Attribute("longdesc", value);
	}

	/// <summary>
	/// Fetch the image at a low priority relative to other images.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Low(string value)
	{
		return this.Attribute("low", value);
	}

	/// <summary>
	/// Equivalent to vertical-align: -moz-middle-with-baseline
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Middle(string value)
	{
		return this.Attribute("middle", value);
	}

	/// <summary>
	/// A name for the element. Use the id attribute instead.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	[Obsolete]
	public Img Name(string value)
	{
		return this.Attribute("name", value);
	}

	/// <summary>
	/// A string indicating which referrer to use when fetching the resource:
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Referrerpolicy(string value)
	{
		return this.Attribute("referrerpolicy", value);
	}

	/// <summary>
	/// Equivalent to float: right
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Right(string value)
	{
		return this.Attribute("right", value);
	}

	/// <summary>
	/// One or more values separated by commas, which can be source sizes or the auto keyword. The spec requires that the sizes attribute to only be present when srcset uses width descriptors.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Sizes(string value)
	{
		return this.Attribute("sizes", value);
	}

	/// <summary>
	/// The image URL. At least one of src and srcset is required for an &lt;img&gt; element. If srcset is specified, src is used in one of two ways:
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Src(string value)
	{
		return this.Attribute("src", value);
	}

	/// <summary>
	/// One or more strings separated by commas, indicating possible image sources for the user agent to use.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Srcset(string value)
	{
		return this.Attribute("srcset", value);
	}

	/// <summary>
	/// Decode the image synchronously along with rendering the other DOM content, and present everything together.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Sync(string value)
	{
		return this.Attribute("sync", value);
	}

	/// <summary>
	/// Equivalent to vertical-align: top or vertical-align: text-top
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Top(string value)
	{
		return this.Attribute("top", value);
	}

	/// <summary>
	/// The CORS request is sent with any credentials included (that is, cookies, X.509 certificates, and the Authorization request header). If the server does not opt into sharing credentials with the origin site (by sending back the Access-Control-Allow-Credentials: true response header), then the browser marks the image as tainted and restricts access to its image data.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img UseCredentials(string value)
	{
		return this.Attribute("use-credentials", value);
	}

	/// <summary>
	/// The partial URL (starting with # ) of an image map associated with the element.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Usemap(string value)
	{
		return this.Attribute("usemap", value);
	}

	/// <summary>
	/// The number of pixels of white space above and below the image. Use the margin CSS property instead.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	[Obsolete]
	public Img Vspace(string value)
	{
		return this.Attribute("vspace", value);
	}

	/// <summary>
	/// The intrinsic width of the image in pixels. Must be an integer without a unit.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
	/// </summary>
	public Img Width(string value)
	{
		return this.Attribute("width", value);
	}

}
