// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ins

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;ins&gt; HTML element represents a range of text that has been added to a document. You can use the &lt;del&gt; element to similarly represent a range of text that has been deleted from the document.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ins
/// </summary>
public partial class Ins
	: HtmlTag
{
	/// <summary>
	/// The &lt;ins&gt; HTML element represents a range of text that has been added to a document. You can use the &lt;del&gt; element to similarly represent a range of text that has been deleted from the document.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ins
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Ins(params IEnumerable<IHtmlContent> contents)
		: base("ins", false, contents)
	{
	}

	/// <summary>
	/// The &lt;ins&gt; HTML element represents a range of text that has been added to a document. You can use the &lt;del&gt; element to similarly represent a range of text that has been deleted from the document.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ins
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Ins(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// This attribute defines the URI of a resource that explains the change, such as a link to meeting minutes or a ticket in a troubleshooting system.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ins
	/// </summary>
	public Ins Cite(string value)
	{
		return this.Attribute("cite", value);
	}

	/// <summary>
	/// This attribute indicates the time and date of the change and must be a valid date with an optional time string. If the value cannot be parsed as a date with an optional time string, the element does not have an associated timestamp. For the format of the string without a time, see Format of a valid date string. The format of the string if it includes both date and time is covered in Format of a valid local date and time string.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ins
	/// </summary>
	public Ins Datetime(string value)
	{
		return this.Attribute("datetime", value);
	}

}
