// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The <legend> HTML element represents a caption for the content of its parent <fieldset>. In customizable <select> elements, the <legend> element is allowed as a child of <optgroup>, to provide a label that is easy to target and style. This replaces any text set in the <optgroup> element's label attribute, and it has the same semantics.
/// </summary>
public partial class Legend(params IEnumerable<IHtmlContent> contents)
	: HtmlTag("legend", false, contents)
{
	public Legend(string text)
		: this(Encode(text))
	{
	}
}
