// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;link&gt; HTML element specifies relationships between the current document and an external resource.
/// This element is most commonly used to link to stylesheets, but is also used to establish site icons (both &quot;favicon&quot; style icons and icons for the home screen and apps on mobile devices) among other things.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
///<br/> - by Mozilla Contributors
/// </summary>
public partial class Link
	: HtmlTag
{
	/// <summary>
	/// The &lt;link&gt; HTML element specifies relationships between the current document and an external resource.
	/// This element is most commonly used to link to stylesheets, but is also used to establish site icons (both &quot;favicon&quot; style icons and icons for the home screen and apps on mobile devices) among other things.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link()
		: base("link", true)
	{
	}
	/// <summary>
	/// A cross-origin request (i.e., with an Origin HTTP header) is performed, but no credential is sent (i.e., no cookie, X.509 certificate, or HTTP Basic authentication).
	/// If the server does not give credentials to the origin site (by not setting the Access-Control-Allow-Origin HTTP header) the resource will be tainted and its usage restricted.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Anonymous(string value)
	{
		return this.Attribute("anonymous", value);
	}

	/// <summary>
	/// This attribute is required when rel=&quot;preload&quot; has been set on the &lt;link&gt; element, optional when rel=&quot;modulepreload&quot; has been set, and otherwise should not be used.
	/// It specifies the type of content being loaded by the &lt;link&gt;, which is necessary for request matching, application of correct content security policy, and setting of correct Accept request header.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link As(string value)
	{
		return this.Attribute("as", value);
	}

	/// <summary>
	/// Don&apos;t set a preference for the fetch priority.
	/// This is the default.
	/// It is used if no value or an invalid value is set.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Auto(string value)
	{
		return this.Attribute("auto", value);
	}

	/// <summary>
	/// This attribute explicitly indicates that certain operations should be blocked until specific conditions are met. It must only be used when the rel attribute contains the expect or stylesheet keywords. With rel=&quot;expect&quot;, it indicates that operations should be blocked until a specific DOM node has been parsed. With rel=&quot;stylesheet&quot;, it indicates that operations should be blocked until an external stylesheet and its critical subresources have been fetched and applied to the document. The operations that are to be blocked must be a space-separated list of blocking tokens listed below. Currently there is only one token:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Blocking(string value)
	{
		return this.Attribute("blocking", value);
	}

	/// <summary>
	/// This attribute defines the character encoding of the linked resource.
	/// The value is a space- and/or comma-delimited list of character sets as defined in RFC 2045.
	/// The default value is iso-8859-1.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Link Charset(string value)
	{
		return this.Attribute("charset", value);
	}

	/// <summary>
	/// This enumerated attribute indicates whether CORS must be used when fetching the resource.
	///  CORS-enabled images can be reused in the &lt;canvas&gt; element without being tainted.
	/// The allowed values are:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Crossorigin(string value)
	{
		return this.Attribute("crossorigin", value);
	}

	/// <summary>
	/// For rel=&quot;stylesheet&quot; only, the disabled Boolean attribute indicates whether the described stylesheet should be loaded and applied to the document.
	/// If disabled is specified in the HTML when it is loaded, the stylesheet will not be loaded during page load.
	/// Instead, the stylesheet will be loaded on-demand, if and when the disabled attribute is changed to false or removed.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Disabled(string value)
	{
		return this.Attribute("disabled", value);
	}

	/// <summary>
	/// Provides a hint of the relative priority to use when fetching a resource of a particular type. Allowed values:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Fetchpriority(string value)
	{
		return this.Attribute("fetchpriority", value);
	}

	/// <summary>
	/// Fetch the resource at a high priority relative to other resources of the same type.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link High(string value)
	{
		return this.Attribute("high", value);
	}

	/// <summary>
	/// This attribute specifies the URL of the linked resource. A URL can be absolute or relative.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Href(string value)
	{
		return this.Attribute("href", value);
	}

	/// <summary>
	/// This attribute indicates the language of the linked resource.
	/// It is purely advisory.
	/// Values should be valid BCP 47 language tags.
	/// Use this attribute only if the href attribute is present.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Hreflang(string value)
	{
		return this.Attribute("hreflang", value);
	}

	/// <summary>
	/// For rel=&quot;preload&quot; and as=&quot;image&quot; only, the imagesizes attribute has similar syntax and semantics as the sizes attribute that indicates to preload the appropriate resource used by an img element with corresponding values for its srcset and sizes attributes.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Imagesizes(string value)
	{
		return this.Attribute("imagesizes", value);
	}

	/// <summary>
	/// For rel=&quot;preload&quot; and as=&quot;image&quot; only, the imagesrcset attribute has similar syntax and semantics as the srcset attribute that indicates to preload the appropriate resource used by an img element with corresponding values for its srcset and sizes attributes.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Imagesrcset(string value)
	{
		return this.Attribute("imagesrcset", value);
	}

	/// <summary>
	/// Contains inline metadata â a base64-encoded cryptographic hash of the resource (file) you&apos;re telling the browser to fetch.
	/// The browser can use this to verify that the fetched resource has been delivered without unexpected manipulation.
	/// The attribute must only be specified when the rel attribute is specified to stylesheet, preload, or modulepreload.
	/// See Subresource Integrity.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Integrity(string value)
	{
		return this.Attribute("integrity", value);
	}

	/// <summary>
	/// Fetch the resource at a low priority relative to other resources of the same type.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Low(string value)
	{
		return this.Attribute("low", value);
	}

	/// <summary>
	/// This attribute specifies the media that the linked resource applies to. Its value must be a media type / media query.
	/// This attribute is mainly useful when linking to external stylesheets â it allows the user agent to pick the best adapted one for the device it runs on.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Media(string value)
	{
		return this.Attribute("media", value);
	}

	/// <summary>
	/// A string indicating which referrer to use when fetching the resource. For detailed explanations and examples of each policy, see the Referrer-Policy header documentation.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Referrerpolicy(string value)
	{
		return this.Attribute("referrerpolicy", value);
	}

	/// <summary>
	/// This attribute names a relationship of the linked document to the current document. The attribute must be a space-separated list of link type values.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Rel(string value)
	{
		return this.Attribute("rel", value);
	}

	/// <summary>
	/// The value of this attribute shows the relationship of the current document to the linked document, as defined by the href attribute.
	/// The attribute thus defines the reverse relationship compared to the value of the rel attribute.
	///  Link type values for the attribute are similar to the possible values for rel.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Link Rev(string value)
	{
		return this.Attribute("rev", value);
	}

	/// <summary>
	/// This attribute defines the sizes of the icons for visual media contained in the resource.
	/// It must be present only if the rel contains a value of icon or a non-standard type such as Apple&apos;s apple-touch-icon.
	/// It may have the following values:
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Sizes(string value)
	{
		return this.Attribute("sizes", value);
	}

	/// <summary>
	/// Defines the frame or window name that has the defined linking relationship or that will show the rendering of any linked resource.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Link Target(string value)
	{
		return this.Attribute("target", value);
	}

	/// <summary>
	/// The title attribute has special semantics on the &lt;link&gt; element.
	/// When used on a &lt;link rel=&quot;stylesheet&quot;&gt; it defines a default or an alternate stylesheet.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public new Link Title(string value)
	{
		return this.Attribute("title", value);
	}

	/// <summary>
	/// This attribute is used to define the type of the content linked to.
	/// The value of the attribute should be a MIME type such as text/html, text/css, and so on.
	/// The common use of this attribute is to define the type of stylesheet being referenced (such as text/css ), but given that CSS is the only stylesheet language used on the web, not only is it possible to omit the type attribute, but is actually now recommended practice.
	/// It is also used on rel=&quot;preload&quot; link types, to make sure the browser only downloads file types that it supports.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link Type(string value)
	{
		return this.Attribute("type", value);
	}

	/// <summary>
	/// A cross-origin request (i.e., with an Origin HTTP header) is performed along with a credential sent (i.e., a cookie, certificate, and/or HTTP Basic authentication is performed).
	/// If the server does not give credentials to the origin site (through Access-Control-Allow-Credentials HTTP header), the resource will be tainted and its usage restricted.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/link
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Link UseCredentials(string value)
	{
		return this.Attribute("use-credentials", value);
	}

}
