// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;

/// <summary>
/// The <map> HTML element is used with <area> elements to define an image map (a clickable link area).
/// </summary>
public partial class Map(IHtmlContent content)
	: HtmlTag("map", false, content)
{
	/// <summary>
	/// The name attribute gives the map a name so that it can be referenced. The attribute must be present and must have a non-empty value with no space characters. The value of the name attribute must not be equal to the value of the name attribute of another <map> element in the same document. If the id attribute is also specified, both attributes must have the same value.
	/// </summary>
	public Map Name(string value)
	{
		return this.Attribute("name", value);
	}

}
