// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;marquee&gt; HTML element is used to insert a scrolling area of text. You can control what happens when the text reaches the edges of its content area using its attributes. The HTML &lt;marquee&gt; element is deprecated and its use is strongly discouraged. If you must create the effect of scrolling text or continuous elements, consider using CSS animations with CSS transforms instead of &lt;marquee&gt; elements to smoothly animate content. Additionally, include the prefers-reduced-motion CSS @media query to stop the animation based on user preference, thereby improving user experience and accessibility.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
///<br/> - by Mozilla Contributors
/// </summary>
[Obsolete]
public partial class Marquee
	: HtmlTag
{
	/// <summary>
	/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;marquee&gt; HTML element is used to insert a scrolling area of text. You can control what happens when the text reaches the edges of its content area using its attributes. The HTML &lt;marquee&gt; element is deprecated and its use is strongly discouraged. If you must create the effect of scrolling text or continuous elements, consider using CSS animations with CSS transforms instead of &lt;marquee&gt; elements to smoothly animate content. Additionally, include the prefers-reduced-motion CSS @media query to stop the animation based on user preference, thereby improving user experience and accessibility.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Marquee(params IEnumerable<IHtmlContent> contents)
		: base("marquee", false, contents)
	{
	}

	/// <summary>
	/// Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;marquee&gt; HTML element is used to insert a scrolling area of text. You can control what happens when the text reaches the edges of its content area using its attributes. The HTML &lt;marquee&gt; element is deprecated and its use is strongly discouraged. If you must create the effect of scrolling text or continuous elements, consider using CSS animations with CSS transforms instead of &lt;marquee&gt; elements to smoothly animate content. Additionally, include the prefers-reduced-motion CSS @media query to stop the animation based on user preference, thereby improving user experience and accessibility.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Marquee(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// Sets how the text is scrolled within the marquee. Possible values are scroll, slide and alternate. If no value is specified, the default value is scroll.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Behavior(string value)
	{
		return this.Attribute("behavior", value);
	}

	/// <summary>
	/// Sets the background color through color name or hexadecimal value.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Bgcolor(string value)
	{
		return this.Attribute("bgcolor", value);
	}

	/// <summary>
	/// Sets the direction of the scrolling within the marquee. Possible values are left, right, up and down. If no value is specified, the default value is left.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Direction(string value)
	{
		return this.Attribute("direction", value);
	}

	/// <summary>
	/// Sets the height in pixels or percentage value.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Height(string value)
	{
		return this.Attribute("height", value);
	}

	/// <summary>
	/// Sets the horizontal margin
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Hspace(string value)
	{
		return this.Attribute("hspace", value);
	}

	/// <summary>
	/// Sets the number of times the marquee will scroll. If no value is specified, the default value is â1, which means the marquee will scroll continuously.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Loop(string value)
	{
		return this.Attribute("loop", value);
	}

	/// <summary>
	/// Sets the amount of scrolling at each interval in pixels. The default value is 6.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Scrollamount(string value)
	{
		return this.Attribute("scrollamount", value);
	}

	/// <summary>
	/// Sets the interval between each scroll movement in milliseconds. The default value is 85. Note that any value smaller than 60 is ignored and the value 60 is used instead unless truespeed is specified.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Scrolldelay(string value)
	{
		return this.Attribute("scrolldelay", value);
	}

	/// <summary>
	/// By default, scrolldelay values lower than 60 are ignored. If truespeed is present, those values are not ignored.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Truespeed(string value)
	{
		return this.Attribute("truespeed", value);
	}

	/// <summary>
	/// Sets the vertical margin in pixels or percentage value.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Vspace(string value)
	{
		return this.Attribute("vspace", value);
	}

	/// <summary>
	/// Sets the width in pixels or percentage value.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/marquee
	///<br/> - by Mozilla Contributors
	/// </summary>
	[Obsolete]
	public Marquee Width(string value)
	{
		return this.Attribute("width", value);
	}

}
