// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;meta&gt; HTML element represents metadata that cannot be represented by other meta-related elements, such as &lt;base&gt;, &lt;link&gt;, &lt;script&gt;, &lt;style&gt;, or &lt;title&gt;. The type of metadata provided by the &lt;meta&gt; element can be one of the following: If the name attribute is set, the &lt;meta&gt; element provides document-level metadata that applies to the whole page. If the http-equiv attribute is set, the &lt;meta&gt; element acts as a pragma directive to simulate directives that could otherwise be given by an HTTP header. If the charset attribute is set, the &lt;meta&gt; element is a charset declaration, giving the character encoding in which the document is encoded. If the itemprop attribute is set, the &lt;meta&gt; element provides user-defined metadata.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta
/// </summary>
public partial class Meta
	: HtmlTag
{
	/// <summary>
	/// The &lt;meta&gt; HTML element represents metadata that cannot be represented by other meta-related elements, such as &lt;base&gt;, &lt;link&gt;, &lt;script&gt;, &lt;style&gt;, or &lt;title&gt;. The type of metadata provided by the &lt;meta&gt; element can be one of the following: If the name attribute is set, the &lt;meta&gt; element provides document-level metadata that applies to the whole page. If the http-equiv attribute is set, the &lt;meta&gt; element acts as a pragma directive to simulate directives that could otherwise be given by an HTTP header. If the charset attribute is set, the &lt;meta&gt; element is a charset declaration, giving the character encoding in which the document is encoded. If the itemprop attribute is set, the &lt;meta&gt; element provides user-defined metadata.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta
	/// </summary>
	public Meta()
		: base("meta", true)
	{
	}
	/// <summary>
	/// This attribute declares the document&apos;s character encoding. If the attribute is present, its value must be an ASCII case-insensitive match for the string &quot;utf-8&quot;, because UTF-8 is the only valid encoding for HTML5 documents. &lt;meta&gt; elements which declare a character encoding must be located entirely within the first 1024 bytes of the document.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta
	/// </summary>
	public Meta Charset(string value)
	{
		return this.Attribute("charset", value);
	}

	/// <summary>
	/// This attribute contains the value for the http-equiv or name attribute, depending on which is used.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta
	/// </summary>
	public Meta Content(string value)
	{
		return this.Attribute("content", value);
	}

	/// <summary>
	/// Defines a pragma directive, which are instructions for the browser for processing the document.
	/// The attribute&apos;s name is short for http-equivalent because the allowed values are names of equivalent HTTP headers.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta
	/// </summary>
	public Meta HttpEquiv(string value)
	{
		return this.Attribute("http-equiv", value);
	}

	/// <summary>
	/// The media attribute defines which media the theme color defined in the content attribute should be applied to.
	/// Its value is a media query, which defaults to all if the attribute is missing.
	/// This attribute is only relevant when the element&apos;s name attribute is set to theme-color.
	/// Otherwise, it has no effect, and should not be included.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta
	/// </summary>
	public Meta Media(string value)
	{
		return this.Attribute("media", value);
	}

	/// <summary>
	/// The name and content attributes can be used together to provide document metadata in terms of name-value pairs, with the name attribute giving the metadata name, and the content attribute giving the value.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta
	/// </summary>
	public Meta Name(string value)
	{
		return this.Attribute("name", value);
	}

}
