// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;

/// <summary>
/// The <nav> HTML element represents a section of a page whose purpose is to provide navigation links, either within the current document or to other documents. Common examples of navigation sections are menus, tables of contents, and indexes.
/// </summary>
public partial class Nav(IHtmlContent content)
	: HtmlTag("nav", false, content)
{
}
