// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
///Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;noembed&gt; HTML element is an obsolete, non-standard way to provide alternative, or &quot;fallback&quot;, content for browsers that do not support the &lt;embed&gt; element or do not support the type of embedded content an author wishes to use. This element was deprecated in HTML 4.01 and above in favor of placing fallback content between the opening and closing tags of an &lt;object&gt; element. Note: 
///While this element currently still works in many browsers, it is obsolete and should not be used. Use &lt;object&gt; instead, with fallback content between the opening and closing tags of the element.
/// </summary>
[Obsolete]
public partial class Noembed
	: HtmlTag
{
	/// <summary>
	///Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;noembed&gt; HTML element is an obsolete, non-standard way to provide alternative, or &quot;fallback&quot;, content for browsers that do not support the &lt;embed&gt; element or do not support the type of embedded content an author wishes to use. This element was deprecated in HTML 4.01 and above in favor of placing fallback content between the opening and closing tags of an &lt;object&gt; element. Note: 
	///While this element currently still works in many browsers, it is obsolete and should not be used. Use &lt;object&gt; instead, with fallback content between the opening and closing tags of the element.
	/// </summary>
	/// <param name="contents">
	///A list of HTML contents to place inside this element.
	/// </param>
	public Noembed(params IEnumerable<IHtmlContent> contents)
		: base("noembed", false, contents)
	{
	}

	/// <summary>
	///Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time. The &lt;noembed&gt; HTML element is an obsolete, non-standard way to provide alternative, or &quot;fallback&quot;, content for browsers that do not support the &lt;embed&gt; element or do not support the type of embedded content an author wishes to use. This element was deprecated in HTML 4.01 and above in favor of placing fallback content between the opening and closing tags of an &lt;object&gt; element. Note: 
	///While this element currently still works in many browsers, it is obsolete and should not be used. Use &lt;object&gt; instead, with fallback content between the opening and closing tags of the element.
	/// </summary>
	/// <param name="text">
	///Some text to write inside this element. The text will be encoded.
	/// </param>
	public Noembed(string text)
		: this(Encode(text))
	{
	}
}
