// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The <object> HTML element represents an external resource, which can be treated as an image, a nested browsing context, or a resource to be handled by a plugin.
/// </summary>
public partial class Object(params IEnumerable<IHtmlContent> contents)
	: HtmlTag("object", false, contents)
{
	public Object(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// A space-separated list of URIs for archives of resources for the object.
	/// </summary>
	public Object Archive(string value)
	{
		return this.Attribute("archive", value);
	}

	/// <summary>
	/// The width of a border around the control, in pixels.
	/// </summary>
	public Object Border(string value)
	{
		return this.Attribute("border", value);
	}

	/// <summary>
	/// The URI of the object's implementation. It can be used together with, or in place of, the data attribute.
	/// </summary>
	public Object Classid(string value)
	{
		return this.Attribute("classid", value);
	}

	/// <summary>
	/// The base path used to resolve relative URIs specified by classid, data, or archive. If not specified, the default is the base URI of the current document.
	/// </summary>
	public Object Codebase(string value)
	{
		return this.Attribute("codebase", value);
	}

	/// <summary>
	/// The content type of the data specified by classid.
	/// </summary>
	public Object Codetype(string value)
	{
		return this.Attribute("codetype", value);
	}

	/// <summary>
	/// The address of the resource as a valid URL. At least one of data and type must be defined.
	/// </summary>
	public Object Data(string value)
	{
		return this.Attribute("data", value);
	}

	/// <summary>
	/// The presence of this Boolean attribute makes this element a declaration only. The object must be instantiated by a subsequent <object> element. Repeat the <object> element completely each time the resource is reused.
	/// </summary>
	public Object Declare(string value)
	{
		return this.Attribute("declare", value);
	}

	/// <summary>
	/// The form element, if any, that the object element is associated with (its form owner ). The value of the attribute must be an ID of a <form> element in the same document.
	/// </summary>
	public Object Form(string value)
	{
		return this.Attribute("form", value);
	}

	/// <summary>
	/// The height of the displayed resource, as in <integer> in CSS pixels.
	/// </summary>
	public Object Height(string value)
	{
		return this.Attribute("height", value);
	}

	/// <summary>
	/// The name of valid browsing context (HTML5), or the name of the control (HTML 4). The name becomes a property of the Window and Document objects, containing a reference to the embedded window or the element itself.
	/// </summary>
	public Object Name(string value)
	{
		return this.Attribute("name", value);
	}

	/// <summary>
	/// A message that the browser can show while loading the object's implementation and data.
	/// </summary>
	public Object Standby(string value)
	{
		return this.Attribute("standby", value);
	}

	/// <summary>
	/// The content type of the resource specified by data. At least one of data and type must be defined.
	/// </summary>
	public Object Type(string value)
	{
		return this.Attribute("type", value);
	}

	/// <summary>
	/// A hash-name reference to a <map> element; that is a '#' followed by the value of a name of a map element.
	/// </summary>
	public Object Usemap(string value)
	{
		return this.Attribute("usemap", value);
	}

	/// <summary>
	/// The width of the display resource, as in <integer> in CSS pixels.
	/// </summary>
	public Object Width(string value)
	{
		return this.Attribute("width", value);
	}

}
