// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ol

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;ol&gt; HTML element represents an ordered list of items â typically rendered as a numbered list.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ol
/// </summary>
public partial class Ol
	: HtmlTag
{
	/// <summary>
	/// The &lt;ol&gt; HTML element represents an ordered list of items â typically rendered as a numbered list.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ol
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Ol(params IEnumerable<IHtmlContent> contents)
		: base("ol", false, contents)
	{
	}

	/// <summary>
	/// The &lt;ol&gt; HTML element represents an ordered list of items â typically rendered as a numbered list.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ol
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Ol(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// This Boolean attribute hints that the list should be rendered in a compact style. The interpretation of this attribute is browser-specific. Use CSS instead: to give a similar effect as the compact attribute, the CSS property line-height can be used with a value of 80%.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ol
	/// </summary>
	[Obsolete]
	public Ol Compact(string value)
	{
		return this.Attribute("compact", value);
	}

	/// <summary>
	/// This Boolean attribute specifies that the list&apos;s items are in reverse order. Items will be numbered from high to low.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ol
	/// </summary>
	public Ol Reversed(string value)
	{
		return this.Attribute("reversed", value);
	}

	/// <summary>
	/// An integer to start counting from for the list items. Always an Arabic numeral (1, 2, 3, etc.), even when the numbering type is letters or Roman numerals. For example, to start numbering elements from the letter &quot;d&quot; or the Roman numeral &quot;iv,&quot; use start=&quot;4&quot;.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ol
	/// </summary>
	public Ol Start(string value)
	{
		return this.Attribute("start", value);
	}

	/// <summary>
	/// Sets the numbering type:
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ol
	/// </summary>
	public Ol Type(string value)
	{
		return this.Attribute("type", value);
	}

}
