// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/optgroup
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;optgroup&gt; HTML element creates a grouping of options within a &lt;select&gt; element. In customizable &lt;select&gt; elements, the &lt;legend&gt; element is allowed as a child of &lt;optgroup&gt;, to provide a label that is easy to target and style. This replaces any text set in the &lt;optgroup&gt; element&apos;s label attribute, and it has the same semantics.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/optgroup
///<br/> - by Mozilla Contributors
/// </summary>
public partial class Optgroup
	: HtmlTag
{
	/// <summary>
	/// The &lt;optgroup&gt; HTML element creates a grouping of options within a &lt;select&gt; element. In customizable &lt;select&gt; elements, the &lt;legend&gt; element is allowed as a child of &lt;optgroup&gt;, to provide a label that is easy to target and style. This replaces any text set in the &lt;optgroup&gt; element&apos;s label attribute, and it has the same semantics.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/optgroup
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Optgroup(params IEnumerable<IHtmlContent> contents)
		: base("optgroup", false, contents)
	{
	}

	/// <summary>
	/// The &lt;optgroup&gt; HTML element creates a grouping of options within a &lt;select&gt; element. In customizable &lt;select&gt; elements, the &lt;legend&gt; element is allowed as a child of &lt;optgroup&gt;, to provide a label that is easy to target and style. This replaces any text set in the &lt;optgroup&gt; element&apos;s label attribute, and it has the same semantics.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/optgroup
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Optgroup(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// If this Boolean attribute is set, none of the items in this option group is selectable. Often browsers grey out such control and it won&apos;t receive any browsing events, like mouse clicks or focus-related ones.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/optgroup
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Optgroup Disabled(string value)
	{
		return this.Attribute("disabled", value);
	}

	/// <summary>
	/// The name of the group of options, which the browser can use when labeling the options in the user interface. This attribute is mandatory if this element is used.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/optgroup
	///<br/> - by Mozilla Contributors
	/// </summary>
	public Optgroup Label(string value)
	{
		return this.Attribute("label", value);
	}

}
