// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;

/// <summary>
/// The <option> HTML element is used to define an item contained in a <select>, an <optgroup>, or a <datalist> element. As such, <option> can represent menu items in popups and other lists of items in an HTML document.
/// </summary>
public partial class Option(IHtmlContent content)
	: HtmlTag("option", false, content)
{
	/// <summary>
	/// If this Boolean attribute is set, this option is not checkable. Often browsers grey out such control and it won't receive any browsing event, like mouse clicks or focus-related ones. If this attribute is not set, the element can still be disabled if one of its ancestors is a disabled <optgroup> element.
	/// </summary>
	public Option Disabled(string value)
	{
		return this.Attribute("disabled", value);
	}

	/// <summary>
	/// This attribute is text for the label indicating the meaning of the option. If the label attribute isn't defined, its value is that of the element text content.
	/// </summary>
	public Option Label(string value)
	{
		return this.Attribute("label", value);
	}

	/// <summary>
	/// If present, this Boolean attribute indicates that the option is initially selected. If the <option> element is the descendant of a <select> element whose multiple attribute is not set, only one single <option> of this <select> element may have the selected attribute.
	/// </summary>
	public Option Selected(string value)
	{
		return this.Attribute("selected", value);
	}

	/// <summary>
	/// The content of this attribute represents the value to be submitted with the form, should this option be selected. If this attribute is omitted, the value is taken from the text content of the option element.
	/// </summary>
	public Option Value(string value)
	{
		return this.Attribute("value", value);
	}

}
