// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/picture

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;picture&gt; HTML element contains zero or more &lt;source&gt; elements and one &lt;img&gt; element to offer alternative versions of an image for different display/device scenarios. The browser will consider each child &lt;source&gt; element and choose the best match among them. If no matches are foundâor the browser doesn&apos;t support the &lt;picture&gt; elementâthe URL of the &lt;img&gt; element&apos;s src attribute is selected. The selected image is then presented in the space occupied by the &lt;img&gt; element.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/picture
/// </summary>
public partial class Picture
	: HtmlTag
{
	/// <summary>
	/// The &lt;picture&gt; HTML element contains zero or more &lt;source&gt; elements and one &lt;img&gt; element to offer alternative versions of an image for different display/device scenarios. The browser will consider each child &lt;source&gt; element and choose the best match among them. If no matches are foundâor the browser doesn&apos;t support the &lt;picture&gt; elementâthe URL of the &lt;img&gt; element&apos;s src attribute is selected. The selected image is then presented in the space occupied by the &lt;img&gt; element.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/picture
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Picture(params IEnumerable<IHtmlContent> contents)
		: base("picture", false, contents)
	{
	}

	/// <summary>
	/// The &lt;picture&gt; HTML element contains zero or more &lt;source&gt; elements and one &lt;img&gt; element to offer alternative versions of an image for different display/device scenarios. The browser will consider each child &lt;source&gt; element and choose the best match among them. If no matches are foundâor the browser doesn&apos;t support the &lt;picture&gt; elementâthe URL of the &lt;img&gt; element&apos;s src attribute is selected. The selected image is then presented in the space occupied by the &lt;img&gt; element.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/picture
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Picture(string text)
		: this(Encode(text))
	{
	}
}
