// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;

/// <summary>
/// The <script> HTML element is used to embed executable code or data; this is typically used to embed or refer to JavaScript code. The <script> element can also be used with other languages, such as WebGL 's GLSL shader programming language and JSON.
/// </summary>
public partial class Script(IHtmlContent content)
	: HtmlTag("script", false, content)
{
	/// <summary>
	/// The embedded content is treated as a data block, and won't be processed by the browser.
	/// Developers must use a valid MIME type that is not a JavaScript MIME type to denote data blocks.
	/// All of the other attributes will be ignored, including the src attribute.
	/// </summary>
	public Script AnyOtherValue(string value)
	{
		return this.Attribute("any_other_value", value);
	}

	/// <summary>
	/// For classic scripts, if the async attribute is present, then the classic script will be fetched in parallel to parsing and evaluated as soon as it is available.
	/// </summary>
	public Script Async(string value)
	{
		return this.Attribute("async", value);
	}

	/// <summary>
	/// Indicates that the script is a "classic script", containing JavaScript code.
	/// Authors are encouraged to omit the attribute if the script refers to JavaScript code rather than specify a MIME type.
	/// JavaScript MIME types are listed in the IANA media types specification.
	/// </summary>
	public Script AttributeIsNotSetDefaultAnEmptyStringOrAJavascriptMimeType(string value)
	{
		return this.Attribute("attribute_is_not_set_default_an_empty_string_or_a_javascript_mime_type", value);
	}

	/// <summary>
	/// Specifies that you want the browser to send an Attribution-Reporting-Eligible header along with the script resource request. On the server-side this is used to trigger sending an Attribution-Reporting-Register-Source or Attribution-Reporting-Register-Trigger header in the response, to register a JavaScript-based attribution source or attribution trigger, respectively. Which response header should be sent back depends on the value of the Attribution-Reporting-Eligible header that triggered the registration.
	/// </summary>
	public Script Attributionsrc(string value)
	{
		return this.Attribute("attributionsrc", value);
	}

	/// <summary>
	/// Don't set a preference for the fetch priority.
	/// This is the default.
	/// It is used if no value or an invalid value is set.
	/// </summary>
	public Script Auto(string value)
	{
		return this.Attribute("auto", value);
	}

	/// <summary>
	/// This attribute explicitly indicates that certain operations should be blocked until the script has executed. The operations that are to be blocked must be a space-separated list of blocking tokens. Currently there is only one token:
	/// </summary>
	public Script Blocking(string value)
	{
		return this.Attribute("blocking", value);
	}

	/// <summary>
	/// If present, its value must be an ASCII case-insensitive match for utf-8. It's unnecessary to specify the charset attribute, because documents must use UTF-8, and the script element inherits its character encoding from the document.
	/// </summary>
	public Script Charset(string value)
	{
		return this.Attribute("charset", value);
	}

	/// <summary>
	/// Normal script elements pass minimal information to the window.onerror for scripts which do not pass the standard CORS checks. To allow error logging for sites which use a separate domain for static media, use this attribute. See CORS settings attributes for a more descriptive explanation of its valid arguments.
	/// </summary>
	public Script Crossorigin(string value)
	{
		return this.Attribute("crossorigin", value);
	}

	/// <summary>
	/// This Boolean attribute is set to indicate to a browser that the script is meant to be executed after the document has been parsed, but before firing DOMContentLoaded event.
	/// </summary>
	public Script Defer(string value)
	{
		return this.Attribute("defer", value);
	}

	/// <summary>
	/// Provides a hint of the relative priority to use when fetching an external script. Allowed values:
	/// </summary>
	public Script Fetchpriority(string value)
	{
		return this.Attribute("fetchpriority", value);
	}

	/// <summary>
	/// Fetch the external script at a high priority relative to other external scripts.
	/// </summary>
	public Script High(string value)
	{
		return this.Attribute("high", value);
	}

	/// <summary>
	/// This value indicates that the body of the element contains an import map.
	/// The import map is a JSON object that developers can use to control how the browser resolves module specifiers when importing JavaScript modules.
	/// </summary>
	public Script Importmap(string value)
	{
		return this.Attribute("importmap", value);
	}

	/// <summary>
	/// This attribute contains inline metadata that a user agent can use to verify that a fetched resource has been delivered without unexpected manipulation. The attribute must not be specified when the src attribute is absent. See Subresource Integrity.
	/// </summary>
	public Script Integrity(string value)
	{
		return this.Attribute("integrity", value);
	}

	/// <summary>
	/// Like the type attribute, this attribute identifies the scripting language in use. Unlike the type attribute, however, this attribute's possible values were never standardized. The type attribute should be used instead.
	/// </summary>
	public Script Language(string value)
	{
		return this.Attribute("language", value);
	}

	/// <summary>
	/// Fetch the external script at a low priority relative to other external scripts.
	/// </summary>
	public Script Low(string value)
	{
		return this.Attribute("low", value);
	}

	/// <summary>
	/// This value causes the code to be treated as a JavaScript module.
	/// The processing of the script contents is deferred.
	/// The charset and defer attributes have no effect.
	/// For information on using module, see our JavaScript modules guide.
	/// Unlike classic scripts, module scripts require the use of the CORS protocol for cross-origin fetching.
	/// </summary>
	public Script Module(string value)
	{
		return this.Attribute("module", value);
	}

	/// <summary>
	/// This Boolean attribute is set to indicate that the script should not be executed in browsers that support ES modules â in effect, this can be used to serve fallback scripts to older browsers that do not support modular JavaScript code.
	/// </summary>
	public Script Nomodule(string value)
	{
		return this.Attribute("nomodule", value);
	}

	/// <summary>
	/// A cryptographic nonce (number used once) to allow scripts in a script-src Content-Security-Policy. The server must generate a unique nonce value each time it transmits a policy. It is critical to provide a nonce that cannot be guessed as bypassing a resource's policy is otherwise trivial.
	/// </summary>
	public Script Nonce(string value)
	{
		return this.Attribute("nonce", value);
	}

	/// <summary>
	/// Indicates which referrer to send when fetching the script, or resources fetched by the script:
	/// </summary>
	public Script Referrerpolicy(string value)
	{
		return this.Attribute("referrerpolicy", value);
	}

	/// <summary>
	/// This value indicates that the body of the element contains speculation rules.
	/// Speculation rules take the form of a JSON object that determine what resources should be prefetched or prerendered by the browser. This is part of the Speculation Rules API.
	/// </summary>
	public Script Speculationrules(string value)
	{
		return this.Attribute("speculationrules", value);
	}

	/// <summary>
	/// This attribute specifies the URI of an external script; this can be used as an alternative to embedding a script directly within a document.
	/// </summary>
	public Script Src(string value)
	{
		return this.Attribute("src", value);
	}

	/// <summary>
	/// This attribute indicates the type of script represented.
	/// The value of this attribute will be one of the following:
	/// </summary>
	public Script Type(string value)
	{
		return this.Attribute("type", value);
	}

}
