// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/section
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;section&gt; HTML element represents a generic standalone section of a document, which doesn&apos;t have a more specific semantic element to represent it. Sections should always have a heading, with very few exceptions.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/section
///<br/> - by Mozilla Contributors
/// </summary>
public partial class Section
	: HtmlTag
{
	/// <summary>
	/// The &lt;section&gt; HTML element represents a generic standalone section of a document, which doesn&apos;t have a more specific semantic element to represent it. Sections should always have a heading, with very few exceptions.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/section
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Section(params IEnumerable<IHtmlContent> contents)
		: base("section", false, contents)
	{
	}

	/// <summary>
	/// The &lt;section&gt; HTML element represents a generic standalone section of a document, which doesn&apos;t have a more specific semantic element to represent it. Sections should always have a heading, with very few exceptions.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/section
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Section(string text)
		: this(Encode(text))
	{
	}
}
