// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// The article by Mozilla Contributors can be found at:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/selectedcontent
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// Experimental: This is an experimental technology Check the Browser compatibility table carefully before using this in production. The &lt;selectedcontent&gt; HTML is used inside a &lt;select&gt; element to display the contents of its currently selected &lt;option&gt; within its first child &lt;button&gt;. This enables you to style all parts of a &lt;select&gt; element, referred to as &quot; customizable selects &quot;.
///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/selectedcontent
///<br/> - by Mozilla Contributors
/// </summary>
public partial class Selectedcontent
	: HtmlTag
{
	/// <summary>
	/// Experimental: This is an experimental technology Check the Browser compatibility table carefully before using this in production. The &lt;selectedcontent&gt; HTML is used inside a &lt;select&gt; element to display the contents of its currently selected &lt;option&gt; within its first child &lt;button&gt;. This enables you to style all parts of a &lt;select&gt; element, referred to as &quot; customizable selects &quot;.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/selectedcontent
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Selectedcontent(params IEnumerable<IHtmlContent> contents)
		: base("selectedcontent", false, contents)
	{
	}

	/// <summary>
	/// Experimental: This is an experimental technology Check the Browser compatibility table carefully before using this in production. The &lt;selectedcontent&gt; HTML is used inside a &lt;select&gt; element to display the contents of its currently selected &lt;option&gt; within its first child &lt;button&gt;. This enables you to style all parts of a &lt;select&gt; element, referred to as &quot; customizable selects &quot;.
	///<br/> <b>This documentation text is derived from MDN and licensed under CC BY-SA 2.5:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/selectedcontent
	///<br/> - by Mozilla Contributors
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Selectedcontent(string text)
		: this(Encode(text))
	{
	}
}
