// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;select&gt; HTML element represents a control that provides a menu of options.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
/// </summary>
public partial class Select
	: HtmlTag
{
	/// <summary>
	/// The &lt;select&gt; HTML element represents a control that provides a menu of options.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Select(params IEnumerable<IHtmlContent> contents)
		: base("select", false, contents)
	{
	}

	/// <summary>
	/// The &lt;select&gt; HTML element represents a control that provides a menu of options.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Select(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// A string providing a hint for a user agent&apos;s autocomplete feature. See The HTML autocomplete attribute for a complete list of values and details on how to use autocomplete.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
	/// </summary>
	public Select Autocomplete(string value)
	{
		return this.Attribute("autocomplete", value);
	}

	/// <summary>
	/// This Boolean attribute lets you specify that a form control should have input focus when the page loads. Only one form element in a document can have the autofocus attribute.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
	/// </summary>
	public new Select Autofocus(string value)
	{
		return this.Attribute("autofocus", value);
	}

	/// <summary>
	/// This Boolean attribute indicates that the user cannot interact with the control. If this attribute is not specified, the control inherits its setting from the containing element, for example &lt;fieldset&gt; ; if there is no containing element with the disabled attribute set, then the control is enabled.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
	/// </summary>
	public Select Disabled(string value)
	{
		return this.Attribute("disabled", value);
	}

	/// <summary>
	/// The &lt;form&gt; element to associate the &lt;select&gt; with (its form owner ). The value of this attribute must be the id of a &lt;form&gt; in the same document. (If this attribute is not set, the &lt;select&gt; is associated with its ancestor &lt;form&gt; element, if any.)
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
	/// </summary>
	public Select Form(string value)
	{
		return this.Attribute("form", value);
	}

	/// <summary>
	/// This Boolean attribute indicates that multiple options can be selected in the list. If it is not specified, then only one option can be selected at a time. When multiple is specified, most browsers will show a scrolling list box instead of a single line dropdown. Multiple selected options are submitted using the URLSearchParams array convention, i.e., name=value1&amp;name=value2.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
	/// </summary>
	public Select Multiple(string value)
	{
		return this.Attribute("multiple", value);
	}

	/// <summary>
	/// This attribute is used to specify the name of the control.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
	/// </summary>
	public Select Name(string value)
	{
		return this.Attribute("name", value);
	}

	/// <summary>
	/// A Boolean attribute indicating that an option with a non-empty string value must be selected.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
	/// </summary>
	public Select Required(string value)
	{
		return this.Attribute("required", value);
	}

	/// <summary>
	/// If the control is presented as a scrolling list box (e.g., when multiple is specified), this attribute represents the number of rows in the list that should be visible at one time. Browsers are not required to present a select element as a scrolled list box. The default value is 0.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select
	/// </summary>
	public Select Size(string value)
	{
		return this.Attribute("size", value);
	}

}
