// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/sub

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;sub&gt; HTML element specifies inline text which should be displayed as subscript for solely typographical reasons. Subscripts are typically rendered with a lowered baseline using smaller text.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/sub
/// </summary>
public partial class Sub
	: HtmlTag
{
	/// <summary>
	/// The &lt;sub&gt; HTML element specifies inline text which should be displayed as subscript for solely typographical reasons. Subscripts are typically rendered with a lowered baseline using smaller text.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/sub
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Sub(params IEnumerable<IHtmlContent> contents)
		: base("sub", false, contents)
	{
	}

	/// <summary>
	/// The &lt;sub&gt; HTML element specifies inline text which should be displayed as subscript for solely typographical reasons. Subscripts are typically rendered with a lowered baseline using smaller text.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/sub
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Sub(string text)
		: this(Encode(text))
	{
	}
}
