// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tbody

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;tbody&gt; HTML element encapsulates a set of table rows ( &lt;tr&gt; elements), indicating that they comprise the body of a table&apos;s (main) data.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tbody
/// </summary>
public partial class Tbody
	: HtmlTag
{
	/// <summary>
	/// The &lt;tbody&gt; HTML element encapsulates a set of table rows ( &lt;tr&gt; elements), indicating that they comprise the body of a table&apos;s (main) data.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tbody
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Tbody(params IEnumerable<IHtmlContent> contents)
		: base("tbody", false, contents)
	{
	}

	/// <summary>
	/// The &lt;tbody&gt; HTML element encapsulates a set of table rows ( &lt;tr&gt; elements), indicating that they comprise the body of a table&apos;s (main) data.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tbody
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Tbody(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// Specifies the horizontal alignment of each body cell. The possible enumerated values are left, center, right, justify, and char. When supported, the char value aligns the textual content on the character defined in the char attribute and on offset defined by the charoff attribute. Use the text-align CSS property instead, as this attribute is deprecated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tbody
	/// </summary>
	[Obsolete]
	public Tbody Align(string value)
	{
		return this.Attribute("align", value);
	}

	/// <summary>
	/// Defines the background color of each body cell. The value is an HTML color; either a 6-digit hexadecimal RGB code, prefixed by a #, or a color keyword. Other CSS &lt;color&gt; values are not supported. Use the background-color CSS property instead, as this attribute is deprecated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tbody
	/// </summary>
	[Obsolete]
	public Tbody Bgcolor(string value)
	{
		return this.Attribute("bgcolor", value);
	}

	/// <summary>
	/// Specifies the alignment of the content to a character of each body cell. Typical values for this include a period (. ) when attempting to align numbers or monetary values. If align is not set to char, this attribute is ignored.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tbody
	/// </summary>
	[Obsolete]
	public Tbody Char(string value)
	{
		return this.Attribute("char", value);
	}

	/// <summary>
	/// Specifies the number of characters to offset the body cell content from the alignment character specified by the char attribute.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tbody
	/// </summary>
	[Obsolete]
	public Tbody Charoff(string value)
	{
		return this.Attribute("charoff", value);
	}

	/// <summary>
	/// Specifies the vertical alignment of each body cell. The possible enumerated values are baseline, bottom, middle, and top. Use the vertical-align CSS property instead, as this attribute is deprecated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/tbody
	/// </summary>
	[Obsolete]
	public Tbody Valign(string value)
	{
		return this.Attribute("valign", value);
	}

}
