// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The <td> HTML element defines a cell of a table that contains data and may be used as a child of the <tr> element.
/// </summary>
public partial class Td(params IEnumerable<IHtmlContent> contents)
	: HtmlTag("td", false, contents)
{
	public Td(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// Contains a short abbreviated description of the data cell's content. Some user-agents, such as speech readers, may present this description before the content itself. Put the abbreviated content inside the cell and place the (longer) description in the title attribute, as this attribute is deprecated. Or, preferably, include the content within the data cell, and use CSS to visually clip overflowing text.
	/// </summary>
	public Td Abbr(string value)
	{
		return this.Attribute("abbr", value);
	}

	/// <summary>
	/// Specifies the horizontal alignment of the data cell. The possible enumerated values are left, center, right, justify, and char. When supported, the char value aligns the textual content on the character defined in the char attribute and the offset defined by the charoff attribute. Use the text-align CSS property instead, as this attribute is deprecated.
	/// </summary>
	public Td Align(string value)
	{
		return this.Attribute("align", value);
	}

	/// <summary>
	/// Contains a list of space-separated strings, each corresponding to the id attribute of a group of cells that the data cell applies to.
	/// </summary>
	public Td Axis(string value)
	{
		return this.Attribute("axis", value);
	}

	/// <summary>
	/// Defines the background color of the data cell. The value is an HTML color; either a 6-digit hexadecimal RGB code, prefixed by a #, or a color keyword. Other CSS <color> values are not supported. Use the background-color CSS property instead, as this attribute is deprecated.
	/// </summary>
	public Td Bgcolor(string value)
	{
		return this.Attribute("bgcolor", value);
	}

	/// <summary>
	/// Does nothing. It was originally intended to specify the alignment of the content to a character of the data cell. Typical values for this include a period (. ) when attempting to align numbers or monetary values. If align is not set to char, this attribute is ignored.
	/// </summary>
	public Td Char(string value)
	{
		return this.Attribute("char", value);
	}

	/// <summary>
	/// Does nothing. It was originally intended to specify the number of characters to offset the data cell content from the alignment character specified by the char attribute.
	/// </summary>
	public Td Charoff(string value)
	{
		return this.Attribute("charoff", value);
	}

	/// <summary>
	/// Contains a non-negative integer value that indicates how many columns the data cell spans or extends. The default value is 1. User agents dismiss values higher than 1000 as incorrect, setting to the default value ( 1 ).
	/// </summary>
	public Td Colspan(string value)
	{
		return this.Attribute("colspan", value);
	}

	/// <summary>
	/// Contains a list of space-separated strings, each corresponding to the id attribute of the <th> elements that provide headings for this table cell.
	/// </summary>
	public Td Headers(string value)
	{
		return this.Attribute("headers", value);
	}

	/// <summary>
	/// Defines a recommended data cell height. Use the height CSS property instead, as this attribute is deprecated.
	/// </summary>
	public Td Height(string value)
	{
		return this.Attribute("height", value);
	}

	/// <summary>
	/// Contains a non-negative integer value that indicates for how many rows the data cell spans or extends. The default value is 1 ; if its value is set to 0, it extends until the end of the table grouping section ( <thead>, <tbody>, <tfoot>, even if implicitly defined), that the cell belongs to. Values higher than 65534 are clipped to 65534.
	/// </summary>
	public Td Rowspan(string value)
	{
		return this.Attribute("rowspan", value);
	}

	/// <summary>
	/// Defines the cells that the header (defined in the <th> ) element relates to. The possible enumerated values are row, col, rowgroup, and colgroup. Only use this attribute with the <th> element to define the row or column for which it is a header, as this attribute is deprecated for the <td> element.
	/// </summary>
	public Td Scope(string value)
	{
		return this.Attribute("scope", value);
	}

	/// <summary>
	/// Specifies the vertical alignment of the data cell. The possible enumerated values are baseline, bottom, middle, and top. Use the vertical-align CSS property instead, as this attribute is deprecated.
	/// </summary>
	public Td Valign(string value)
	{
		return this.Attribute("valign", value);
	}

	/// <summary>
	/// Defines a recommended data cell width. Use the width CSS property instead, as this attribute is deprecated.
	/// </summary>
	public Td Width(string value)
	{
		return this.Attribute("width", value);
	}

}
