// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;th&gt; HTML element defines a cell as the header of a group of table cells and may be used as a child of the &lt;tr&gt; element. The exact nature of this group is defined by the scope and headers attributes.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
/// </summary>
public partial class Th
	: HtmlTag
{
	/// <summary>
	/// The &lt;th&gt; HTML element defines a cell as the header of a group of table cells and may be used as a child of the &lt;tr&gt; element. The exact nature of this group is defined by the scope and headers attributes.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Th(params IEnumerable<IHtmlContent> contents)
		: base("th", false, contents)
	{
	}

	/// <summary>
	/// The &lt;th&gt; HTML element defines a cell as the header of a group of table cells and may be used as a child of the &lt;tr&gt; element. The exact nature of this group is defined by the scope and headers attributes.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Th(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// A short, abbreviated description of the header cell&apos;s content provided as an alternative label to use for the header cell when referencing the cell in other contexts. Some user-agents, such as screen readers, may present this description before the content itself.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	public Th Abbr(string value)
	{
		return this.Attribute("abbr", value);
	}

	/// <summary>
	/// Specifies the horizontal alignment of the header cell. The possible enumerated values are left, center, right, justify, and char. When supported, the char value aligns the textual content on the character defined in the char attribute and the offset defined by the charoff attribute. Use the text-align CSS property instead, as this attribute is deprecated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	[Obsolete]
	public Th Align(string value)
	{
		return this.Attribute("align", value);
	}

	/// <summary>
	/// Contains a list of space-separated strings, each corresponding to the id attribute of a group of cells that the header cell applies to. Use the scope attribute instead, as this attribute is deprecated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	[Obsolete]
	public Th Axis(string value)
	{
		return this.Attribute("axis", value);
	}

	/// <summary>
	/// Defines the background color of the header cell. The value is an HTML color; either a 6-digit hexadecimal RGB code, prefixed by a #, or a color keyword. Other CSS &lt;color&gt; values are not supported. Use the background-color CSS property instead, as this attribute is deprecated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	[Obsolete]
	public Th Bgcolor(string value)
	{
		return this.Attribute("bgcolor", value);
	}

	/// <summary>
	/// Does nothing. It was originally intended to specify the alignment of the content to a character of the header cell. Typical values for this include a period (. ) when attempting to align numbers or monetary values. If align is not set to char, this attribute is ignored.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	[Obsolete]
	public Th Char(string value)
	{
		return this.Attribute("char", value);
	}

	/// <summary>
	/// Does nothing. It was originally intended to specify the number of characters to offset the header cell content from the alignment character specified by the char attribute.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	[Obsolete]
	public Th Charoff(string value)
	{
		return this.Attribute("charoff", value);
	}

	/// <summary>
	/// A non-negative integer value indicating how many columns the header cell spans or extends. The default value is 1. User agents dismiss values higher than 1000 as incorrect, defaulting such values to 1.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	public Th Colspan(string value)
	{
		return this.Attribute("colspan", value);
	}

	/// <summary>
	/// A list of space-separated strings corresponding to the id attributes of the &lt;th&gt; elements that provide the headers for this header cell.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	public Th Headers(string value)
	{
		return this.Attribute("headers", value);
	}

	/// <summary>
	/// Defines a recommended header cell height. Use the height CSS property instead, as this attribute is deprecated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	[Obsolete]
	public Th Height(string value)
	{
		return this.Attribute("height", value);
	}

	/// <summary>
	/// A non-negative integer value indicating how many rows the header cell spans or extends. The default value is 1 ; if its value is set to 0, the header cell will extend to the end of the table grouping section ( &lt;thead&gt;, &lt;tbody&gt;, &lt;tfoot&gt;, even if implicitly defined), that the &lt;th&gt; belongs to. Values higher than 65534 are clipped at 65534.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	public Th Rowspan(string value)
	{
		return this.Attribute("rowspan", value);
	}

	/// <summary>
	/// Defines the cells that the header (defined in the &lt;th&gt; ) element relates to. Possible enumerated values are:
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	public Th Scope(string value)
	{
		return this.Attribute("scope", value);
	}

	/// <summary>
	/// Specifies the vertical alignment of the header cell. The possible enumerated values are baseline, bottom, middle, and top. Use the vertical-align CSS property instead, as this attribute is deprecated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	[Obsolete]
	public Th Valign(string value)
	{
		return this.Attribute("valign", value);
	}

	/// <summary>
	/// Defines a recommended header cell width. Use the width CSS property instead, as this attribute is deprecated.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/th
	/// </summary>
	[Obsolete]
	public Th Width(string value)
	{
		return this.Attribute("width", value);
	}

}
