// <auto-generated/>
#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The <ul> HTML element represents an unordered list of items, typically rendered as a bulleted list.
/// </summary>
public partial class Ul(params IEnumerable<IHtmlContent> contents)
	: HtmlTag("ul", false, contents)
{
	public Ul(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// This Boolean attribute hints that the list should be rendered in a compact style. The interpretation of this attribute is browser-specific. Use CSS instead: to give a similar effect as the compact attribute, the CSS property line-height can be used with a value of 80%.
	/// </summary>
	[Obsolete]
	public Ul Compact(string value)
	{
		return this.Attribute("compact", value);
	}

	/// <summary>
	/// This attribute sets the bullet style for the list. The values defined under HTML3.2 and the transitional version of HTML 4.0/4.01 are:
	/// </summary>
	[Obsolete]
	public Ul Type(string value)
	{
		return this.Attribute("type", value);
	}

}
