// <auto-generated/>

// This file contains documentation text derived from Mozilla Developer Network (MDN) Web Docs.
// MDN content is licensed under CC BY-SA 2.5:
// https://creativecommons.org/licenses/by-sa/2.5/

// The source of the documentation is:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ul

// All other code in this file is licensed under the Apache License 2.0.

#nullable enable
namespace RobinEpple.Common.Html.Components;

using RobinEpple.Common.Html;
using RobinEpple.Common.Html.Components;
using Microsoft.AspNetCore.Html;
using static RobinEpple.Common.Html.DSL;

/// <summary>
/// The &lt;ul&gt; HTML element represents an unordered list of items, typically rendered as a bulleted list.
///<br/> <b>Source:</b>
///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ul
/// </summary>
public partial class Ul
	: HtmlTag
{
	/// <summary>
	/// The &lt;ul&gt; HTML element represents an unordered list of items, typically rendered as a bulleted list.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ul
	/// </summary>
	/// <param name="contents">
	/// A list of HTML contents to place inside this element.
	/// </param>
	public Ul(params IEnumerable<IHtmlContent> contents)
		: base("ul", false, contents)
	{
	}

	/// <summary>
	/// The &lt;ul&gt; HTML element represents an unordered list of items, typically rendered as a bulleted list.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ul
	/// </summary>
	/// <param name="text">
	/// Some text to write inside this element. The text will be encoded.
	/// </param>
	public Ul(string text)
		: this(Encode(text))
	{
	}
	/// <summary>
	/// This Boolean attribute hints that the list should be rendered in a compact style. The interpretation of this attribute is browser-specific. Use CSS instead: to give a similar effect as the compact attribute, the CSS property line-height can be used with a value of 80%.
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ul
	/// </summary>
	[Obsolete]
	public Ul Compact(string value)
	{
		return this.Attribute("compact", value);
	}

	/// <summary>
	/// This attribute sets the bullet style for the list. The values defined under HTML3.2 and the transitional version of HTML 4.0/4.01 are:
	///<br/> <b>Source:</b>
	///<br/> https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/ul
	/// </summary>
	[Obsolete]
	public Ul Type(string value)
	{
		return this.Attribute("type", value);
	}

}
