<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>RobinEpple.Common.Html</AssemblyName>
        <PackageId>RobinEpple.Common.Html</PackageId>
        <RootNamespace>RobinEpple.Common.Html</RootNamespace>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Title>A html rendering library offering a declarative-functional api based on the MDN documentation.</Title>

        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>./_generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <None Include="_generated\**\*.cs" />
        <Compile Remove="_generated\**\*.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Html.Abstractions" />
        <PackageReference Include="RobinEpple.Common.SourceGenerators" PrivateAssets="all" ExcludeAssets="runtime" />
    </ItemGroup>

</Project>
