<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>RobinEpple.Common.SourceGenerators.Test</AssemblyName>
        <RootNamespace>RobinEpple.Common.SourceGenerators.Test</RootNamespace>

        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>./_generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <None Include="_generated\**\*.cs" />
        <Compile Remove="_generated\**\*.cs" />
    </ItemGroup>

    <ItemGroup>
        <None Include="ReferenceImplementation\**\*.cs" />
        <Compile Remove="ReferenceImplementation\**\*.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="MSTest" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="RobinEpple.Common.SourceGenerators" PrivateAssets="all" ExcludeAssets="runtime" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    </ItemGroup>
</Project>
