namespace RobinEpple.Common.SourceGenerators;

using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using RobinEpple.Common.SourceGenerators.Abstractions;

[Generator]
public class AsyncOverloadGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Find candidate methods that have a [GenerateAsyncOverload] attribute.
		var methods = context
			.SyntaxProvider.CreateSyntaxProvider(
				predicate: static (syntaxNode, _) => IsCandidate(syntaxNode),
				transform: static (context, _) => GetTarget(context)
			)
			.Where(m => m is not null);

		// Combine with the bigger compilation context to have access to other classes in the assembly.
		var compilationAndMethods = context.CompilationProvider.Combine(methods.Collect());

		// Register the source code factory.
		context.RegisterSourceOutput(compilationAndMethods, Generate);
	}

	private static bool IsCandidate(SyntaxNode node) => node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0;

	private static MethodDeclarationSyntax? GetTarget(GeneratorSyntaxContext context)
	{
		var methodDeclaration = (MethodDeclarationSyntax)context.Node;

		foreach (var attr in methodDeclaration.AttributeLists.SelectMany(attributeList => attributeList.Attributes))
		{
			var symbol = context.SemanticModel.GetSymbolInfo(attr).Symbol;
			if (
				symbol is IMethodSymbol methodSymbol
				&& methodSymbol.ContainingType.ToDisplayString() == typeof(GenerateAsyncOverloadAttribute).FullName
			)
			{
				return methodDeclaration;
			}
		}

		return null;
	}

	private record GenerationTask
	{
		public MethodDeclarationSyntax? MethodDeclaration { get; set; }
		public IMethodSymbol? MethodSymbol { get; set; }
		public SemanticModel? SemanticModel { get; set; }
		public string? AsyncName { get; set; }
		public bool IsComplete =>
			MethodDeclaration != null && MethodSymbol != null && SemanticModel != null && AsyncName != null;
	}

	private static void Generate(
		SourceProductionContext context,
		(Compilation Compilation, ImmutableArray<MethodDeclarationSyntax?> MethodDeclarations) generatorInformation
	)
	{
		var compilation = generatorInformation.Compilation;

		// Keep in mind the async overloads that will be generated when translating.
		var generationTasks = generatorInformation
			.MethodDeclarations.Select(methodDeclaration =>
			{
				if (methodDeclaration == null)
				{
					return new GenerationTask();
				}

				var semanticModel = compilation.GetSemanticModel(methodDeclaration.SyntaxTree);
				var methodSymbol = semanticModel.GetDeclaredSymbol(methodDeclaration);
				if (methodSymbol == null)
				{
					return new GenerationTask();
				}

				var asyncName = methodSymbol.Name + "Async";
				return new GenerationTask
				{
					MethodDeclaration = methodDeclaration,
					MethodSymbol = methodSymbol,
					SemanticModel = semanticModel,
					AsyncName = asyncName,
				};
			})
			.Where(task => task.IsComplete)
			.ToList();

		var toBeGeneratedAsyncMethodNamesBySyncOverload = generationTasks.ToDictionary<
			GenerationTask,
			IMethodSymbol,
			string
		>(task => task.MethodSymbol!, task => task.AsyncName!, SymbolEqualityComparer.Default);

		foreach (var generationTask in generationTasks)
		{
			var methodDeclaration = generationTask.MethodDeclaration!;
			var methodSymbol = generationTask.MethodSymbol!;
			var semanticModel = generationTask.SemanticModel!;
			var asyncName = generationTask.AsyncName!;

			var classDeclaration = methodDeclaration.FirstAncestorOrSelf<ClassDeclarationSyntax>();
			if (classDeclaration == null)
			{
				return;
			}

			var classSymbol = compilation
				.GetSemanticModel(classDeclaration.SyntaxTree)
				.GetDeclaredSymbol(classDeclaration);
			if (classSymbol == null)
			{
				return;
			}

			var classNamespace = classSymbol.ContainingNamespace.ToDisplayString();

			var sb = new StringBuilder();

			// Auto generated marker.
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine();

			// Namespace declaration.
			sb.AppendLine($"namespace {classNamespace};");
			sb.AppendLine();

			// Rebuild class declaration with modifiers
			sb.AppendLine(BuildClassDeclarationHeader(classDeclaration));
			sb.AppendLine("{");

			// Inherit the documentation from the original.
			sb.AppendLine(IndentHelper.Indent(BuildInheritdoc(methodSymbol)));

			// Find all awaitable overloads in the methods.
			var awaitableOverloadLocator = new AwaitableOverloadLocator(toBeGeneratedAsyncMethodNamesBySyncOverload);
			var awaitableOverloads = awaitableOverloadLocator.FindAwaitableOverloadsInMethod(
				methodDeclaration,
				semanticModel
			);

			// Build the async signature.
			sb.AppendLine(IndentHelper.Indent(BuildAsyncMethodSignature(generationTask, awaitableOverloads)));

			// Body: naive clone + replace Foo() -> await FooAsync()
			sb.AppendLine(
				IndentHelper.Indent(BuildAsyncMethodBody(methodDeclaration, compilation, awaitableOverloads))
			);

			// Close class.
			sb.AppendLine("}");

			// Add the source code to the compilation.
			context.AddSource(
				$"{classDeclaration.Identifier.Text}.{methodSymbol.Name}.Async.g.cs",
				SourceText.From(sb.ToString(), Encoding.UTF8)
			);
		}
	}

	private static string BuildClassDeclarationHeader(ClassDeclarationSyntax classDeclaration)
	{
		var sb = new StringBuilder();

		// Declare modifiers.
		var classModifiers = string.Join(" ", classDeclaration.Modifiers.Select(m => m.Text));
		sb.Append(classModifiers);

		// Declare the class.
		sb.Append(" class ");
		sb.Append(classDeclaration.Identifier.Text);

		// Add type parameters if they exist.
		if (classDeclaration.TypeParameterList != null)
		{
			sb.Append(classDeclaration.TypeParameterList.ToFullString());
		}

		// Build the class declaration.
		return sb.ToString();
	}

	private static string BuildInheritdoc(IMethodSymbol methodSymbol)
	{
		var parameterTypes = string.Join(",", methodSymbol.Parameters.Select(p => p.Type.ToDisplayString()));
		return $"/// <inheritdoc cref=\"{methodSymbol.Name}({parameterTypes})\"/>";
	}

	private static string BuildAsyncMethodSignature(
		GenerationTask generationTask,
		Dictionary<IMethodSymbol, string> awaitableOverloads
	)
	{
		// Return type.
		var returnType = generationTask.MethodSymbol!.ReturnsVoid
			? "System.Threading.Tasks.Task"
			: $"System.Threading.Tasks.Task<{generationTask.MethodSymbol!.ReturnType.ToDisplayString()}>";

		// Modifiers.
		var methodModifiers = generationTask.MethodDeclaration!.Modifiers.Select(m => m.Text).ToList();

		// Only add "async" if at least one call is awaited.
		if (awaitableOverloads.Any())
		{
			methodModifiers.Add("async");
		}

		// Parameters
		var parameters = string.Join(
			", ",
			generationTask.MethodSymbol!.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}")
		);

		return $"{string.Join(" ", methodModifiers)} {returnType} {generationTask.AsyncName}({parameters})";
	}

	private static string BuildAsyncMethodBody(
		MethodDeclarationSyntax methodDeclaration,
		Compilation compilation,
		Dictionary<IMethodSymbol, string> awaitableOverloads
	)
	{
		var semanticModel = compilation.GetSemanticModel(methodDeclaration.SyntaxTree);

		var translator = new AsyncTranslator();
		return translator.TranslateMethodBody(methodDeclaration, semanticModel, awaitableOverloads);
	}
}
