namespace RobinEpple.Common.SourceGenerators;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using RobinEpple.Common.SourceGenerators.Abstractions;

[Generator]
public class StaticFactoryGenerator : IIncrementalGenerator
{
	private static bool _waitForDebugger = false;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		while (_waitForDebugger && !Debugger.IsAttached)
		{
			Thread.Sleep(100);
		}

		// Find candidate classes that have a [StaticFactory] attribute.
		var factoryClasses = context
			.SyntaxProvider.CreateSyntaxProvider(
				predicate: FilterClassesWithAttributes,
				transform: ExtractStaticFactoryAttribute
			)
			.Where(static t => t.symbol is not null);

		// Combine with the bigger compilation context to have access to other classes in the assembly.
		var compilationAndFactories = context.CompilationProvider.Combine(factoryClasses.Collect());

		// Register the source code factory.
		context.RegisterSourceOutput(compilationAndFactories, ExecuteSourceProduction);
	}

	private bool FilterClassesWithAttributes(SyntaxNode node, CancellationToken cancellationToken)
	{
		return node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0;
	}

	private (INamedTypeSymbol symbol, AttributeData attr) ExtractStaticFactoryAttribute(
		GeneratorSyntaxContext ctx,
		CancellationToken cancellationToken
	)
	{
		var classDecl = (ClassDeclarationSyntax)ctx.Node;
		var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl);

		if (symbol is null)
		{
			return default;
		}

		foreach (var attr in symbol.GetAttributes())
		{
			if (attr.AttributeClass?.ToDisplayString() == typeof(StaticFactoryAttribute).FullName)
			{
				return (symbol, attr);
			}
		}
		return default;
	}

	private void ExecuteSourceProduction(
		SourceProductionContext spc,
		(Compilation Compilation, ImmutableArray<(INamedTypeSymbol, AttributeData)> Factories) generatorInformation
	)
	{
		foreach (var (factoryClass, staticFactoryAttribute) in generatorInformation.Factories)
		{
			if (factoryClass is null || staticFactoryAttribute is null)
			{
				continue;
			}

			if (staticFactoryAttribute.ConstructorArguments.Length != 1)
			{
				continue;
			}
			var markerInterface = staticFactoryAttribute.ConstructorArguments[0].Value as INamedTypeSymbol;
			if (markerInterface is null)
			{
				continue;
			}

			// Find all types that implement the marker interface
			var allTypes = GetAllTypes(generatorInformation.Compilation.Assembly.GlobalNamespace);
			var implementingTypes = allTypes.Where(t => !t.IsAbstract && t.AllInterfaces.Contains(markerInterface));

			foreach (var implementingType in implementingTypes)
			{
				GenerateFactoryMethodForType(spc, factoryClass, implementingType);
			}
		}
	}

	private IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns)
	{
		foreach (var member in ns.GetMembers())
		{
			if (member is INamespaceSymbol childNs)
			{
				foreach (var type in GetAllTypes(childNs))
				{
					yield return type;
				}
			}
			else if (member is INamedTypeSymbol type)
			{
				yield return type;
				foreach (var nested in type.GetTypeMembers())
				{
					yield return nested;
				}
			}
		}
	}

	private void GenerateFactoryMethodForType(
		SourceProductionContext spc,
		INamedTypeSymbol factoryClass,
		INamedTypeSymbol interfaceImplementation
	)
	{
		var sb = new StringBuilder();

		// Auto generated marker.
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine();

		// Namespace declaration.
		sb.AppendLine($"namespace {factoryClass.ContainingNamespace.ToDisplayString()};");
		sb.AppendLine();

		// Factory class declaration.
		var accessModifier = string.Join(
			string.Empty,
			factoryClass.DeclaredAccessibility.ToString().Select(char.ToLowerInvariant)
		);
		sb.AppendLine($"{accessModifier} static partial class {factoryClass.Name}");
		sb.AppendLine("{");

		foreach (
			var constructor in interfaceImplementation.Constructors.Where(c =>
				c.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal
			)
		)
		{
			// Copy the documentation of the constructor if available.
			var documentation = constructor.GetDocumentationCommentXml(
				expandIncludes: true,
				cancellationToken: default
			);
			if (!string.IsNullOrWhiteSpace(documentation))
			{
				var xmlLines = documentation!.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries);
				foreach (var line in xmlLines)
				{
					if (line.StartsWith("<member") || line.StartsWith("</member"))
					{
						continue;
					}
					sb.AppendLine("    /// " + line.Trim());
				}
			}

			// Create the method signature.
			var parameters = string.Join(
				", ",
				constructor.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}")
			);
			sb.AppendLine(
				$"    public static {interfaceImplementation.ToDisplayString()} {interfaceImplementation.Name}({parameters})"
			);

			// Call the constructor and return the new object.
			var args = string.Join(", ", constructor.Parameters.Select(p => p.Name));
			sb.AppendLine($"        => new {interfaceImplementation.ToDisplayString()}({args});");
			sb.AppendLine();
		}

		// Close the class declaration.
		sb.AppendLine("}");

		// And add the file to the source code.
		spc.AddSource(
			$"{factoryClass.Name}.{interfaceImplementation.Name}.g.cs",
			SourceText.From(sb.ToString(), Encoding.UTF8)
		);
	}
}
