<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>RobinEpple.Common.Forms.Test</AssemblyName>
        <RootNamespace>RobinEpple.Common.Forms.Test</RootNamespace>

        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>./Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <None Include="Generated\**\*.cs" />
        <Compile Remove="Generated\**\*.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="MSTest" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Common.Forms/Common.Forms.csproj" />
        <PackageReference Include="RobinEpple.Common.Forms.Wrappers" PrivateAssets="all" ExcludeAssets="runtime" />
        <PackageReference Include="RobinEpple.Common.SourceGenerators" PrivateAssets="all" ExcludeAssets="runtime" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    </ItemGroup>

</Project>
