<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>RobinEpple.Common.Forms</AssemblyName>
        <PackageId>RobinEpple.Common.Forms</PackageId>
        <RootNamespace>RobinEpple.Common.Forms</RootNamespace>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Title>Private Form Engine</Title>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="IbanNet" />
        <PackageReference Include="libphonenumber-csharp" />
        <PackageReference Include="Mime" />
        <PackageReference Include="RobinEpple.Common.Util" />
    </ItemGroup>

</Project>
