<Project>
    <PropertyGroup>
        <Authors>Robin Epple</Authors>

        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <Version>1.0.0.0</Version>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <Optimize>true</Optimize>
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>
</Project>