<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="IbanNet" Version="5.18.0" />
    <PackageVersion Include="libphonenumber-csharp" Version="9.0.3" />
    <PackageVersion Include="Mime" Version="3.7.0" />
    <PackageVersion Include="RobinEpple.Common.Util" Version="1.0.0-beta.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageVersion Include="MSTest" Version="3.6.1" />
  </ItemGroup>
</Project>