#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="BlockBodyWithoutAwaitCalls_ShouldReturnCompletedTask()"/>
	public Task<int> BlockBodyWithoutAwaitCalls_ShouldReturnCompletedTaskAsync()
	{
		return Task.FromResult<int>(42);
	}

}
