#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateCallsInForeachStatements()"/>
	public async Task AsyncOverload_ShouldTranslateCallsInForeachStatementsAsync()
	{
		foreach (var number in await GetArrayAsync())
		{
			await IdentityAsync(number);
		}
	}
}
