#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateAnonymousObjectCreation()"/>
	public async Task AsyncOverload_ShouldTranslateAnonymousObjectCreationAsync()
	{
		var myObject = new
		{
			SomeNumber = await IdentityAsync(1),
			SomeText = await IdentityAsync("Hello World!"),
		};
	}

}
