// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateYieldStatement()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateYieldStatementAsync()
	{
		foreach (var item in await GetArrayAsync())
		{
			if (item < 2)
			{
				yield return await IdentityAsync(item);
			}
			else
			{
				yield break;
			}
		}
	}
}
