#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldCopySignature(int,int,int)"/>
	internal static System.Threading.Tasks.Task<System.DateTime> AsyncOverload_ShouldCopySignatureAsync(int day, int month, int year)
	{
		return System.Threading.Tasks.Task.FromResult<System.DateTime>(new DateTime(year, month, day));
	}

}
