#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldNotTranslateAnonymousFunction()"/>
	public Task AsyncOverload_ShouldNotTranslateAnonymousFunctionAsync()
	{
		var increment = (int i) => Identity(i) + 1;
		increment(2);
		return Task.CompletedTask;
	}

}
