#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateConditionalAccessExpression()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateConditionalAccessExpressionAsync()
	{
		var result = await ((await GetInstanceUnsureAsync())?.GetOneAsync() ?? System.Threading.Tasks.Task.FromResult<int>(default));
	}

}
