#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateBinaryExpression()"/>
	public async Task AsyncOverload_ShouldTranslateBinaryExpressionAsync()
	{
		var result = await IdentityAsync(true) && await IdentityAsync(false);
	}

}
