#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AvailableAsyncOverloads_ShouldBeCalledAndAwaitedInBlockBody()"/>
	public async System.Threading.Tasks.Task AvailableAsyncOverloads_ShouldBeCalledAndAwaitedInBlockBodyAsync()
	{
		var instanceDependency = new AsyncOverloadInstanceDependency();
		await InternalVoidMethodAsync();
		await AsyncOverloadStaticDependency.StaticCallAsync();
		await instanceDependency.InstanceCallAsync();
	}

}
