#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AvailableAsyncOverloads_ShouldBeCalledAndAwaitedInBlockBody()"/>
	public async Task AvailableAsyncOverloads_ShouldBeCalledAndAwaitedInBlockBodyAsync()
	{
		var instanceDependency = new AsyncOverloadInstanceDependency();
		await InternalVoidMethodAsync();
		await AsyncOverloadStaticDependency.StaticCallAsync();
		await instanceDependency.InstanceCallAsync();
		await instanceDependency.CancellableOverloadAsync();
	}

}
