#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldHandleGenericClasses()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldHandleGenericClassesAsync()
	{
		var genericInstance = new AsyncOverloadGenericClass<int>();
		await genericInstance.SetValueAsync(2);
		var value = await genericInstance.GetValueAsync();
	}

}
