#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using RobinEpple.Common.SourceGenerators.Abstractions;

public abstract partial class AsyncOverloadTestAbstractClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldWorkOnAbstractMethodStubs(int,int,int)"/>
	public abstract System.Threading.Tasks.Task<System.DateTime> AsyncOverload_ShouldWorkOnAbstractMethodStubsAsync(int day, int month, int year);
}
