#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateConditionalExpression()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateConditionalExpressionAsync()
	{
		int? result = await GetInstanceUnsureAsync() is { } instance
			? await instance.GetOneAsync()
			: null;
	}

}
