#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AvailableAsyncOverloads_ShouldBeCalledAndAwaitedInExpressionBody()"/>
	public async System.Threading.Tasks.Task AvailableAsyncOverloads_ShouldBeCalledAndAwaitedInExpressionBodyAsync()
		=> await InternalVoidMethodAsync();
}
