#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldNotTranslateQueryExpression()"/>
	public Task AsyncOverload_ShouldNotTranslateQueryExpressionAsync()
	{
		var smallerThanTwo = from item in GetArraySure() where item < 2 select item;
		return Task.CompletedTask;
	}

}
