#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateIsPatternExpression()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateIsPatternExpressionAsync()
	{
		var hasObject = (await GetInstanceUnsureAsync()) is not null;
	}

}
