#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateArrayCreationExpression()"/>
	public async Task AsyncOverload_ShouldTranslateArrayCreationExpressionAsync()
	{
		var array = new int[]
		{
			await IdentityAsync(1),
			await IdentityAsync(2),
		};
		var array2 = new int[5];
	}

}
