#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateCallsInForStatement()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateCallsInForStatementAsync()
	{
		for (int i = 0; i < 10; await IncrementAsync(i))
		{
			await InternalVoidMethodAsync();
		}
	}
}
