#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AvailableAsyncOverloads_ShouldBeCalledAndAwaitedInExpressionBody()"/>
	public async Task AvailableAsyncOverloads_ShouldBeCalledAndAwaitedInExpressionBodyAsync()
		=> await InternalVoidMethodAsync();
}
