#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateOnlyHeadOfLockStatement()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateOnlyHeadOfLockStatementAsync()
	{
		lock (await GetArrayAsync())
		{
			InternalVoidMethod();
		}
	}
}
