#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldFindAsyncOverloadsForExtensions()"/>
	public async Task AsyncOverload_ShouldFindAsyncOverloadsForExtensionsAsync()
	{
		var instance = new AsyncOverloadInstanceDependency();
		await RobinEpple.Common.SourceGenerators.Test.MethodScopedExtensions.InstanceDependencyExtensions.ExtensionCallAsync(instance, 2);
	}

}
