#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateInitializerExpression()"/>
	public async Task AsyncOverload_ShouldTranslateInitializerExpressionAsync()
	{
		var instance = new AsyncOverloadInstanceDependency()
		{
			Counter = await IdentityAsync(3)
		};
	}

}
