#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateCallsInDoWhile()"/>
	public async Task AsyncOverload_ShouldTranslateCallsInDoWhileAsync()
	{
		do
		{
			await InternalVoidMethodAsync();
		} while (false);
	}
}
