#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateMemberBindingExpression()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateMemberBindingExpressionAsync()
	{
		var currentCount = (await GetInstanceUnsureAsync())?.Counter;
	}

}
