#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateCallsInIfStatement()"/>
	public async Task AsyncOverload_ShouldTranslateCallsInIfStatementAsync()
	{
		if (1 < await IncrementAsync(2))
		{
			await InternalVoidMethodAsync();
		}
		else if (2 > await IncrementAsync(3))
		{
			await GetArrayAsync();
		}
		else
		{
			throw new Exception("unexpected result");
		}
	}
}
