#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateIsPatternExpression()"/>
	public async Task AsyncOverload_ShouldTranslateIsPatternExpressionAsync()
	{
		var hasObject = await GetInstanceUnsureAsync() is not null;
	}

}
