#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateParenthesizedExpression()"/>
	public async Task AsyncOverload_ShouldTranslateParenthesizedExpressionAsync()
	{
		var result = (await IdentityAsync(1) + await IdentityAsync(2)) * await IdentityAsync(3);
	}

}
