#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateOnlyHeadOfLockStatement()"/>
	public async Task AsyncOverload_ShouldTranslateOnlyHeadOfLockStatementAsync()
	{
		lock (await GetArrayAsync())
		{
			InternalVoidMethod();
		}
	}
}
