#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldWorkOnInterfaceDeclarations(int,int,int)"/>
	public Task<DateTime> AsyncOverload_ShouldWorkOnInterfaceDeclarationsAsync(int day, int month, int year)
		=> throw new NotImplementedException();
}
