#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslatePostfixUnaryExpression()"/>
	public async Task AsyncOverload_ShouldTranslatePostfixUnaryExpressionAsync()
	{
		(await GetInstanceSureAsync()).Counter++;
	}

}
