#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="BlockBodyWithoutAwaitCalls_ShouldReturnCompletedTask()"/>
	public System.Threading.Tasks.Task<int> BlockBodyWithoutAwaitCalls_ShouldReturnCompletedTaskAsync()
	{
		return System.Threading.Tasks.Task.FromResult<int>(42);
	}

}
