#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateYieldStatement()"/>
	public async IAsyncEnumerable<int> AsyncOverload_ShouldTranslateYieldStatementAsync()
	{
		foreach (var item in await GetArrayAsync())
		{
			if (item < 2)
			{
				yield return await IdentityAsync(item);
			}
			else
			{
				yield break;
			}
		}
	}
}
