#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateInvocationExpression()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateInvocationExpressionAsync()
	{
		await GetInstanceUnsureAsync();
	}

}
