#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldWorkOnMultipleOverloads(int)"/>
	public async Task AsyncOverload_ShouldWorkOnMultipleOverloadsAsync(int firstParam)
	{
		await InternalVoidMethodAsync();
	}

}
