#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;

public abstract partial class AsyncOverloadTestAbstractClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldWorkOnAbstractMethodStubs(int,int,int)"/>
	public abstract Task<DateTime> AsyncOverload_ShouldWorkOnAbstractMethodStubsAsync(int day, int month, int year);
}
