#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateInitializerExpression()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateInitializerExpressionAsync()
	{
		var instance = new AsyncOverloadInstanceDependency()
		{
			Counter = await IdentityAsync(3)
		};
	}

}
