#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateMemberAccessExpression()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateMemberAccessExpressionAsync()
	{
		var result = (await GetInstanceSureAsync()).Two;
	}

}
