#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldWorkOnInterfaceDeclarations(int,int,int)"/>
	public System.Threading.Tasks.Task<System.DateTime> AsyncOverload_ShouldWorkOnInterfaceDeclarationsAsync(int day, int month, int year)
		=> throw new NotImplementedException();
}
