#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateWhileStatement()"/>
	public async System.Threading.Tasks.Task AsyncOverload_ShouldTranslateWhileStatementAsync()
	{
		while (await IdentityAsync(1) < await IncrementAsync(1))
		{
			await InternalVoidMethodAsync();
			continue;
		}
	}
}
