#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using System.Threading.Tasks;
using RobinEpple.Common.SourceGenerators.Abstractions;
using RobinEpple.Common.SourceGenerators.Test.ClassScopedExtensions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldTranslateSwitchStatement()"/>
	public async Task AsyncOverload_ShouldTranslateSwitchStatementAsync()
	{
		switch (await IncrementAsync(1))
		{
			case 1:
			{
				break;
			}
			case 2:
			{
				await InternalVoidMethodAsync();
				return;
			}
			default:
			{
				return;
			}
		}
	}
}
