#nullable enable
// <auto-generated/>

namespace RobinEpple.Common.SourceGenerators.Test;

using RobinEpple.Common.SourceGenerators.Abstractions;

public partial class AsyncOverloadTestClass
{
	/// <inheritdoc cref="AsyncOverload_ShouldWorkOnAbstractMethodStubs(int,int,int)"/>
	public override System.Threading.Tasks.Task<System.DateTime> AsyncOverload_ShouldWorkOnAbstractMethodStubsAsync(int day, int month, int year)
		=> throw new NotImplementedException();
}
